import {el,icon} from './ui.js';
import {searchEntries} from './planner.js';
export function installPalette(ctx){
  let selected=0,entries=[];const list=el('div',{id:'command-results',class:'command-results',role:'listbox','aria-label':'Search results'}),search=el('input',{placeholder:'Find tasks, lists, links or actions…','aria-label':'Search Sebams',role:'combobox','aria-controls':'command-results','aria-expanded':'true',autocomplete:'off'}),dialog=el('dialog',{id:'command-palette',class:'command-palette','aria-label':'Search and commands'},el('div',{class:'command-search'},icon('search'),search,el('button',{class:'text-button',type:'button','aria-label':'Close search',onclick:()=>dialog.close()},'Esc')),list,el('p',{class:'help'},'↑ ↓ to choose · Enter to open · Ctrl+K to search'));
  document.body.append(dialog);
  const commands=[{type:'command',label:'New task',meta:'Quickly add to Inbox',action:()=>ctx.command('new')},{type:'command',label:'Weekly calendar',meta:'Tasks and exams',action:()=>ctx.command('calendar')},{type:'command',label:'Exam planner',meta:'Create a study plan',action:()=>ctx.command('exams')},{type:'command',label:'Templates',meta:'Reusable tasks',action:()=>ctx.command('templates')},{type:'command',label:'Weekly progress',meta:'Completed tasks by subject',action:()=>ctx.command('progress')},{type:'command',label:'Settings',meta:'Personalize Sebams',action:()=>ctx.command('settings')}];
  const choose=ctx.run(async item=>{dialog.close();if(item.action)await item.action();else await ctx.choose(item);});
  const mark=()=>{[...list.querySelectorAll('[role="option"]')].forEach((node,i)=>{node.classList.toggle('selected',i===selected);node.setAttribute('aria-selected',String(i===selected));});const active=entries.length?list.children[selected]:null;if(active){search.setAttribute('aria-activedescendant',active.id);active.scrollIntoView({block:'nearest'});}else search.removeAttribute('aria-activedescendant');};
  const render=()=>{const query=search.value.trim().toLocaleLowerCase();entries=[...commands.filter(c=>!query||c.label.toLocaleLowerCase().includes(query)),...searchEntries(ctx.state(),query)];selected=0;list.replaceChildren(...entries.map((item,i)=>el('button',{id:'command-result-'+i,type:'button',role:'option',tabindex:-1,class:'command-result',onclick:()=>choose(item)},icon(item.type==='link'?'external':item.type==='task'?'check':'list'),el('span',{},el('strong',{},item.label),el('small',{},item.meta)))));if(!entries.length)list.append(el('p',{class:'help'},'No matching tasks, lists or links.'));mark();};
  search.addEventListener('input',render);search.addEventListener('keydown',e=>{if(['ArrowDown','ArrowUp','Enter'].includes(e.key)){e.preventDefault();if(e.key==='Enter'){if(entries[selected])choose(entries[selected]);}else{selected=(selected+(e.key==='ArrowDown'?1:-1)+entries.length)%Math.max(1,entries.length);mark();}}});
  const open=()=>{search.value='';render();if(!dialog.open)dialog.showModal();search.focus();};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();dialog.open?dialog.close():open();}});
  dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});return open;
}
