const ORIGINS=['https://api.open-meteo.com/*','https://geocoding-api.open-meteo.com/*'];
const isExtension=()=>!!globalThis.chrome?.runtime?.id;
export async function hasWeatherAccess(){return !isExtension()||await chrome.permissions.contains({origins:ORIGINS});}
export async function requestWeatherAccess(){return !isExtension()||await chrome.permissions.request({origins:ORIGINS});}
async function json(url){if(!await hasWeatherAccess())throw Error('Enable weather access with Find or Use my location to get new readings.');const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),10000);try{const response=await fetch(url,{signal:controller.signal,credentials:'omit',referrerPolicy:'no-referrer'});if(!response.ok)throw Error('Weather service is temporarily unavailable.');const result=await response.json();if(result.error)throw Error('The weather service could not use this location.');return result;}catch(e){if(e.name==='AbortError')throw Error('Weather took too long to respond.');if(e instanceof TypeError)throw Error('Weather is unavailable while offline.');throw e;}finally{clearTimeout(timeout);}}
export async function searchCities(query){const value=query.trim();if(value.length<2)throw Error('Enter at least two letters of a city name.');const data=await json(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(value)}&count=8&language=en&format=json`);return(data.results||[]).filter(c=>Number.isFinite(c.latitude)&&Number.isFinite(c.longitude)).map(c=>({name:String(c.name).slice(0,100),label:[c.name,c.admin1,c.country].filter(Boolean).join(', ').slice(0,200),latitude:c.latitude,longitude:c.longitude}));}
export async function fetchWeather(city,cached=null,force=false){if(!Number.isFinite(city.latitude)||city.latitude<-90||city.latitude>90||!Number.isFinite(city.longitude)||city.longitude<-180||city.longitude>180)throw Error('Choose a valid weather location.');const cityKey=`${city.latitude},${city.longitude}`;if(!force&&cached?.cityKey===cityKey&&Date.now()-cached.updatedAt>=0&&Date.now()-cached.updatedAt<30*60000)return cached;const data=await json(`https://api.open-meteo.com/v1/forecast?latitude=${city.latitude}&longitude=${city.longitude}&current=temperature_2m,weather_code&temperature_unit=celsius&timezone=auto`);const tempC=data.current?.temperature_2m,code=data.current?.weather_code;if(!Number.isFinite(tempC)||tempC<-100||tempC>70||!Number.isInteger(code)||code<0||code>99)throw Error('The weather service returned an unavailable reading.');return{cityKey,tempC,code,updatedAt:Date.now()};}
export function weatherLabel(code){if(code===0)return'Clear sky';if(code<=3)return'Partly cloudy';if(code===45||code===48)return'Fog';if(code>=51&&code<=57)return'Drizzle';if(code>=61&&code<=67)return'Rain';if(code>=71&&code<=77)return'Snow';if(code>=80&&code<=82)return'Rain showers';if(code===85||code===86)return'Snow showers';if(code>=95)return'Thunderstorms';return'Weather conditions';}
export async function locateCity(){if(!await requestWeatherAccess())throw Error('Weather access was not enabled.');if(!navigator.geolocation)throw Error('Location is unavailable. Choose a city instead.');const position=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,()=>reject(Error('Location was unavailable or declined. You can choose a city instead.')),{enableHighAccuracy:false,timeout:10000,maximumAge:30*60000}));return{name:'Current location',label:'Current location',latitude:Math.round(position.coords.latitude*1000)/1000,longitude:Math.round(position.coords.longitude*1000)/1000};}
