import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {createHash,randomUUID} from 'node:crypto';
import {createLocalServer} from '../../Sebams-Bridge/server.mjs';
import {createUpdater} from '../../Sebams-Bridge/updater.mjs';
const {chromium}=await import(process.env.SEBAMS_PLAYWRIGHT_PACKAGE||'playwright');
const root=fileURLToPath(new URL('../',import.meta.url)),qa=process.env.SEBAMS_QA_DIR;
if(!qa)throw Error('Set SEBAMS_QA_DIR to a workspace test folder.');
await fs.mkdir(qa,{recursive:true});const target=path.join(qa,'extension-'+Date.now()),release=path.join(qa,'release-'+Date.now());await fs.cp(root,target,{recursive:true});await fs.mkdir(path.join(release,'files'),{recursive:true});
const files=[];async function walk(dir){for(const e of await fs.readdir(dir,{withFileTypes:true})){const file=path.join(dir,e.name),rel=path.relative(target,file).replaceAll('\\','/');if(rel.startsWith('tests/')||['tests','package.json','package-lock.json','.gitignore'].includes(rel))continue;if(e.isDirectory())await walk(file);else{let bytes=await fs.readFile(file);if(rel==='manifest.json'){const m=JSON.parse(bytes);m.version='1.8.1';bytes=Buffer.from(JSON.stringify(m,null,2));}const out=path.join(release,'files',rel);await fs.mkdir(path.dirname(out),{recursive:true});await fs.writeFile(out,bytes);files.push({path:rel,size:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')});}}}await walk(target);
await fs.writeFile(path.join(release,'release.json'),JSON.stringify({format:'sebams-local-release',version:'1.8.1',notes:'Browser update test',files}));const config=path.join(qa,'updates.json');await fs.writeFile(config,JSON.stringify({extensionDirectory:target,releaseDirectory:release}));
const token=randomUUID().replaceAll('-',''),updater=createUpdater({configurationFile:config});const server=createLocalServer({token,solver:{configured:false},updater,store:{snapshot:()=>({tasks:[],workspaces:[]}),workspace:async()=>({ok:true}),ack:async()=>({ok:true})}});await new Promise((r,j)=>{server.once('error',j);server.listen(8787,'127.0.0.1',r);});
let context;const results=[],errors=[];
const check=async(name,fn)=>{try{await fn();results.push({name,status:'pass'});console.log('PASS',name);}catch(e){results.push({name,status:'fail',error:e.message});throw e;}};
try{
 context=await chromium.launchPersistentContext(path.join(qa,'profile-'+Date.now()),{executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,viewport:{width:1440,height:900},ignoreDefaultArgs:['--disable-extensions'],args:['--enable-unsafe-extension-debugging']});const page=context.pages()[0];page.setDefaultTimeout(15000);page.setDefaultNavigationTimeout(15000);await page.goto('chrome://extensions/');await page.evaluate(()=>chrome.developerPrivate.updateProfileConfiguration({inDeveloperMode:true}));const cdp=await context.browser().newBrowserCDPSession(),{id}=await cdp.send('Extensions.loadUnpacked',{path:target}),url=`chrome-extension://${id}/newtab.html`;page.on('pageerror',e=>errors.push(e.message));
 const b=name=>page.getByRole('button',{name,exact:true}),action=async name=>{await b(name).click();await page.waitForTimeout(120);},close=async()=>action('Close panel'),state=()=>page.evaluate(async()=>(await import('./lib/store.js')).getState()),waitOrder=async ids=>page.waitForFunction(async ids=>JSON.stringify((await import('./lib/store.js')).getState().workspaces.personal.links.map(l=>l.id))===JSON.stringify(ids),ids);
 await page.goto(url,{waitUntil:'domcontentloaded'});await page.locator('#welcome-skip').click();await page.locator('#welcome').waitFor({state:'hidden'});await page.evaluate(async token=>{chrome.permissions.contains=async()=>true;const m=await import('./lib/store.js'),{createTask}=await import('./lib/planner.js');await m.setBridgeConfig({token});await m.mutate(s=>{s.prefs.onlineSiteIcons=false;s.prefs.remindersOnOpen=false;s.prefs.name='Update preserved';s.workspaces.personal.tasks=[createTask({id:'update-task',text:'Keep tasks and photos',list:'Inbox',priority:'normal',details:'Original reference'})];s.workspaces.personal.links.push({id:'test-third',title:'Example',url:'https://example.com/',folder:'',pinned:true});for(const l of s.workspaces.personal.links)l.pinned=true;});},token);

 await check('Settings saves a shared GitHub source and preserves machine-local installation folders',async()=>{await page.locator('#settings-open').click();await action('Updates');await page.getByText('Release source',{exact:true}).click();await page.getByLabel('Public GitHub repository',{exact:true}).fill('https://github.com/example/sebams');await action('Save release source');const saved=JSON.parse(await fs.readFile(config,'utf8'));assert.equal(saved.githubRepository,'example/sebams');assert.equal(saved.extensionDirectory,target);assert.equal(saved.releaseDirectory,release);await page.getByLabel('Public GitHub repository',{exact:true}).fill('');await action('Save release source');assert.equal(JSON.parse(await fs.readFile(config,'utf8')).githubRepository,'');await close();});
 await check('Links offers direct removal and Undo restores the shortcut and its pin',async()=>{await page.locator('#links-open').click();const title=(await state()).workspaces.personal.links[0].title;await action('Remove shortcut '+title+' from Links');assert.equal((await state()).workspaces.personal.links.length,2);assert.equal(await page.locator('#pinned-links a').count(),2);await action('Undo');assert.equal((await state()).workspaces.personal.links.length,3);assert.equal(await page.locator('#pinned-links a').count(),3);});
 await check('Dragging Links changes and persists the order',async()=>{const before=(await state()).workspaces.personal.links.map(l=>l.id);const rows=page.locator('.quick-link-row');await rows.first().dragTo(rows.last(),{targetPosition:{x:40,y:30}});await waitOrder([before[1],before[2],before[0]]);await page.screenshot({path:path.join(qa,'links.png')});await close();await page.reload({waitUntil:'domcontentloaded'});await page.locator('#pinned-links a').first().waitFor();assert.deepEqual((await state()).workspaces.personal.links.map(l=>l.id),[before[1],before[2],before[0]]);});
 await check('Dragging dashboard pins changes their order without visiting the URL',async()=>{const before=(await state()).workspaces.personal.links.map(l=>l.id);const rows=page.locator('.pin-wrapper');await rows.last().dragTo(rows.first(),{targetPosition:{x:24,y:3}});await waitOrder([before[2],before[0],before[1]]);assert.equal(page.url(),url);});
 await check('Keyboard reorder works in Links and other workspaces stay unchanged',async()=>{const work=(await state()).workspaces.work.links;await page.locator('#links-open').click();const before=(await state()).workspaces.personal.links.map(l=>l.id);await page.locator('.quick-link-row a').first().focus();await page.keyboard.press('Alt+ArrowDown');await waitOrder([before[1],before[0],before[2]]);assert.deepEqual((await state()).workspaces.work.links,work);await close();});
 await check('Tasks has no sidebar footer and panels darken without blur',async()=>{await page.locator('#tasks-open').click();assert.equal(await page.locator('.task-sidebar-footer').count(),0);assert.equal(await page.getByText('Counts show unfinished tasks',{exact:true}).count(),0);const style=await page.locator('#panel').evaluate(e=>({panel:getComputedStyle(e).backdropFilter,backdrop:getComputedStyle(e,'::backdrop').backdropFilter,color:getComputedStyle(e,'::backdrop').backgroundColor}));assert.equal(style.panel,'none');assert.equal(style.backdrop,'none');assert.equal(style.color,'rgba(0, 0, 0, 0.54)');await page.screenshot({path:path.join(qa,'tasks.png')});await action('Open Keep tasks and photos');await page.getByLabel('Attach task photos').setInputFiles(path.join(root,'assets/backgrounds/alpine.jpg'));await page.locator('.task-photo img').waitFor();await page.getByLabel('Task details',{exact:true}).fill('User reference draft');await close();});
 await check('Update settings check the real local release and show its version',async()=>{await page.evaluate(()=>{chrome.permissions.contains=async()=>true;});const worker=context.serviceWorkers().find(w=>w.url().includes(id));await worker.evaluate(()=>{chrome.permissions.contains=async()=>true;});await page.locator('#settings-open').click();await action('Updates');await action('Check for updates');await b('Check for updates').waitFor();assert.ok(await b('Install update').isVisible(),await page.locator('.bridge-status').textContent());assert.match(await page.locator('.bridge-status').textContent(),/1.8.1/);await page.screenshot({path:path.join(qa,'updates.png')});});
 await check('A changed release fails safely, saves the current task draft, and allows checking again',async()=>{const metadata=JSON.parse(await fs.readFile(path.join(release,'release.json'),'utf8'));metadata.notes='Updated browser release';await fs.writeFile(path.join(release,'release.json'),JSON.stringify(metadata));await action('Install update');await page.getByText('The prepared release changed. Check for updates again.',{exact:true}).waitFor();assert.equal(JSON.parse(await fs.readFile(path.join(target,'manifest.json'),'utf8')).version,'1.8.0');assert.equal((await state()).workspaces.personal.tasks[0].details,'User reference draft');assert.equal((await state()).workspaces.personal.tasks[0].attachments.length,1);await action('Check for updates');await b('Check for updates').waitFor();assert.ok(await b('Install update').isVisible());});

 await check('Concurrent update metadata writes preserve the automatic-check preference',async()=>{const value=await page.evaluate(async()=>{const m=await import('./lib/store.js');await Promise.all([m.patchUpdatePreferences({autoCheck:true}),m.patchUpdatePreferences({lastCheckedAt:Date.now(),availableVersion:'1.8.1'})]);const result=await m.getUpdatePreferences();await m.patchUpdatePreferences({autoCheck:false});return result;});assert.equal(value.autoCheck,true);assert.equal(value.availableVersion,'1.8.1');});
 await check('Daily automatic checks use an alarm, can be disabled, and stay out of backups',async()=>{const worker=context.serviceWorkers().filter(w=>w.url().includes(id)).at(-1);await worker.evaluate(()=>{chrome.permissions.contains=async()=>true;});await page.getByLabel('Check for updates automatically').check();await page.waitForFunction(async()=>!!await chrome.alarms.getAll().then(alarms=>alarms.find(a=>a.name==='sebams-update-check')));const synced=await page.evaluate(()=>chrome.runtime.sendMessage({type:'update-sync'}));assert.equal(synced.ok,true);assert.equal(synced.updates.enabled,true,JSON.stringify(synced));const alarm=await page.evaluate(()=>chrome.alarms.getAll().then(alarms=>alarms.find(a=>a.name==='sebams-update-check')));assert.equal(alarm?.periodInMinutes,1440);const scheduled=alarm.scheduledTime;await page.evaluate(()=>chrome.runtime.sendMessage({type:'update-sync'}));assert.equal((await page.evaluate(()=>chrome.alarms.getAll().then(alarms=>alarms.find(a=>a.name==='sebams-update-check')))).scheduledTime,scheduled);const backup=await page.evaluate(async()=>(await import('./lib/store.js')).exportBackup());assert.ok(!JSON.stringify(backup).includes(token));assert.ok(!JSON.stringify(backup).includes('autoCheck'));await page.getByLabel('Check for updates automatically').uncheck();await page.waitForFunction(async()=>!await chrome.alarms.getAll().then(alarms=>alarms.find(a=>a.name==='sebams-update-check')));});
 await check('Installing updates the actual extension folder, reloads Chrome and preserves data and identity',async()=>{const before=await state(),imageBefore=await page.evaluate(async()=>{const m=await import('./lib/store.js'),blob=await m.getTaskAttachment(m.getState().workspaces.personal.tasks[0].attachments[0].id);return [...new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))];});await action('Install update');await page.waitForFunction(()=>globalThis.chrome?.runtime?.getManifest?.()?.version==='1.8.1',null,{timeout:30000});await page.locator('#clock').waitFor();const after=await state();assert.equal(after.prefs.name,'Update preserved');assert.deepEqual(after.workspaces,before.workspaces);const imageAfter=await page.evaluate(async()=>{const m=await import('./lib/store.js'),blob=await m.getTaskAttachment(m.getState().workspaces.personal.tasks[0].attachments[0].id);return [...new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))];});assert.deepEqual(imageAfter,imageBefore);assert.equal(new URL(page.url()).host,id);const installed=JSON.parse(await fs.readFile(path.join(target,'manifest.json'),'utf8'));assert.equal(installed.version,'1.8.1');assert.ok((await fs.readdir(path.join(qa,'Sebams-version-backups'))).length>0);});
 await check('After reload, Check for updates reports current version',async()=>{await page.evaluate(()=>{chrome.permissions.contains=async()=>true;});await page.locator('#settings-open').click();await action('Updates');await action('Check for updates');await page.getByText('You’re up to date.',{exact:true}).waitFor();assert.equal(await b('Install update').count(),0);});
 await check('Narrow Links layout remains inside the screen with remove controls',async()=>{await close();await page.setViewportSize({width:375,height:812});await page.locator('#links-open').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const rect=await page.locator('#panel').boundingBox();assert.ok(rect.x>=0&&rect.x+rect.width<=376);assert.equal(await page.locator('.shortcut-delete').count(),3);await page.screenshot({path:path.join(qa,'links-mobile.png')});});
 assert.deepEqual(errors,[]);console.log('PASS No page errors');results.push({name:'No page errors',status:'pass'});
}catch(error){await context?.pages()[0]?.screenshot({path:path.join(qa,'failure.png')}).catch(()=>{});console.error(error);const inspect=await context?.newPage();if(inspect){await inspect.goto('chrome://extensions/');console.log('RELOAD DIAGNOSTIC',await inspect.evaluate(async()=>{if(!chrome.developerPrivate)return {available:false};const info=await chrome.developerPrivate.getExtensionsInfo({includeDisabled:true,includeTerminated:true});return info.filter(e=>e.name.includes('Sebams')).map(e=>({name:e.name,id:e.id,state:e.state,disableReasons:e.disableReasons,manifestErrors:e.manifestErrors,runtimeErrors:e.runtimeErrors,version:e.version}));}).catch(e=>({error:e.message})));}process.exitCode=1;}
finally{await fs.writeFile(path.join(root,'tests/results/updates.json'),JSON.stringify({results,errors},null,2));await context?.close();await new Promise(r=>server.close(r));}
