import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.SEBAMS_PLAYWRIGHT_PACKAGE||'playwright');
const root=fileURLToPath(new URL('../',import.meta.url)),qaDir=process.env.SEBAMS_QA_DIR||path.join(root,'work','qa');await fs.mkdir(qaDir,{recursive:true});
const context=await chromium.launchPersistentContext(path.join(qaDir,'upgrade-profile-'+Date.now()),{executablePath:process.env.CHROME_PATH||(process.platform==='win32'?'C:/Program Files/Google/Chrome/Application/chrome.exe':chromium.executablePath()),headless:true,viewport:{width:1440,height:900},ignoreDefaultArgs:['--disable-extensions'],args:['--enable-unsafe-extension-debugging']});
const page=context.pages()[0]||await context.newPage(),cdp=await context.browser().newBrowserCDPSession(),loaded=await cdp.send('Extensions.loadUnpacked',{path:root});
const url=`chrome-extension://${loaded.id}/newtab.html`,results=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
const button=name=>page.getByRole('button',{name,exact:true});
const open=async name=>{await page.locator('#'+name+'-open').click();await page.locator('#panel').waitFor({state:'visible'});if(name==='links'){await page.getByRole('button',{name:'Links options',exact:true}).click();await page.getByRole('button',{name:'Manage links',exact:true}).click();}};
const close=async()=>{await button('Close panel').click();await page.locator('#panel').waitFor({state:'hidden'});};
const snapshot=()=>page.evaluate(async()=>{const m=await import('./lib/store.js');return(await m.exportBackup()).state;});
async function test(name,fn){await fn();results.push({name,status:'pass'});console.log('PASS',name);}
let legacy,dates;
try{
 await page.goto(url);await page.locator('#welcome-skip').click();await page.locator('#welcome').waitFor({state:'hidden'});
 dates=await page.evaluate(async()=>{const {localDay}=await import('./lib/model.js');const day=localDay(),next=new Date(day+'T12:00:00'),prior=new Date(day+'T12:00:00');next.setDate(next.getDate()+1);prior.setDate(prior.getDate()-1);return{day,next:localDay(next),prior:localDay(prior)};});
 await test('Existing version 1 disk data upgrades without losing content',async()=>{
  legacy=await page.evaluate(async()=>{const m=await import('./lib/store.js');const s=(await m.exportBackup()).state;s.schemaVersion=1;(await import('./tests/fixtures.mjs')).stripProduct(s);delete s.photos;for(const key of Object.keys((await import('./lib/model.js')).APPEARANCE_DEFAULTS))delete s.prefs[key];s.revision+=10;s.prefs.name='Taylor';s.workspaces.personal.notes='My existing private note';s.workspaces.personal.widgets.links=false;s.focus.text='Write a thoughtful brief';s.workspaces.personal.tasks=[{id:'legacy-task',text:'My existing task',done:false,priority:'high',list:'Inbox'}];for(const v of [s.prefs.widgets,...Object.values(s.workspaces).map(w=>w.widgets)])for(const key of Object.keys(v))if(!['links','search','weather','tasks'].includes(key))delete v[key];for(const w of Object.values(s.workspaces))for(const link of w.links)delete link.pinned;await new Promise((resolve,reject)=>{const req=indexedDB.open('sebams-v1');req.onsuccess=()=>{const db=req.result,tx=db.transaction('data','readwrite');tx.objectStore('data').put(s,'state');tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);};req.onerror=()=>reject(req.error);});return s;});
  await page.reload();await page.waitForFunction(()=>document.querySelector('#greeting').textContent.includes('Taylor'));const state=await snapshot();assert.equal(state.schemaVersion,6);assert.equal(state.workspaces.personal.notes,legacy.workspaces.personal.notes);assert.equal(state.workspaces.personal.tasks[0].dueDate,'');assert.equal(state.workspaces.personal.widgets.links,false);assert.equal(state.workspaces.personal.widgets.notes,true);
  await open('settings');await page.getByRole('checkbox',{name:'Quick links and pins',exact:true}).check();await close();await page.locator('#links-open').waitFor({state:'visible'});
 });
 await test('Task dates add, edit, clear, filter, complete, delete and undo',async()=>{
  await open('tasks');await page.getByLabel('New task',{exact:true}).fill('Send design notes');await page.getByLabel('Date for new task',{exact:true}).fill(dates.day);await button('Add').click();await page.getByText('Send design notes',{exact:true}).waitFor();await page.getByLabel('Task dates',{exact:true}).selectOption('today');assert.equal(await page.getByText('My existing task',{exact:true}).count(),0);
  await button('Edit Send design notes').click();await page.getByLabel('Task date',{exact:true}).fill(dates.next);await button('Save').click();await page.getByLabel('Task dates',{exact:true}).selectOption('upcoming');await page.getByText('Send design notes',{exact:true}).waitFor();await page.getByText('Tomorrow',{exact:true}).waitFor();await button('Edit Send design notes').click();await page.getByLabel('Task date',{exact:true}).fill('');await button('Save').click();await page.getByLabel('Task dates',{exact:true}).selectOption('undated');await page.getByText('Send design notes',{exact:true}).waitFor();
  await page.getByLabel('New task',{exact:true}).fill('An overdue task');await page.getByLabel('Date for new task',{exact:true}).fill(dates.prior);await button('Add').click();await page.getByText('An overdue task',{exact:true}).waitFor();await page.getByLabel('Task dates',{exact:true}).selectOption('overdue');await page.getByText(/Overdue ·/).waitFor();await page.getByLabel('Complete An overdue task',{exact:true}).click();await page.getByText('An overdue task',{exact:true}).waitFor({state:'hidden'});assert.equal((await snapshot()).workspaces.personal.tasks.find(t=>t.text==='An overdue task').done,true);
  await page.getByLabel('Task dates',{exact:true}).selectOption('all');await button('Delete An overdue task').click();await page.getByText('Task deleted.',{exact:true}).waitFor();await button('Undo').click();await page.getByText('An overdue task',{exact:true}).waitFor();assert.equal((await snapshot()).workspaces.personal.tasks.find(t=>t.text==='An overdue task').dueDate,dates.prior);await close();
 });
 await test('Six new visibility switches persist separately by workspace',async()=>{
  const switches=[['Quick notes','notes-open'],['Focus timer','timer-open'],['Habits','habits-open'],['Main daily focus','daily-focus'],['Background selector','background-open'],['Background favorite button','background-favorite']];
  await open('settings');for(const [name] of switches)await page.getByRole('checkbox',{name,exact:true}).uncheck();await close();for(const [,id] of switches)await page.locator('#'+id).waitFor({state:'hidden'});assert.equal((await snapshot()).workspaces.personal.notes,'My existing private note');
  await open('settings');await button('Workspace').click();await button('Work').click();await close();for(const [,id] of switches)await page.locator('#'+id).waitFor({state:'visible'});await open('settings');await button('Personal').click();await close();for(const [,id] of switches)await page.locator('#'+id).waitFor({state:'hidden'});
  await open('settings');await button('General').click();for(const [name] of switches)await page.getByRole('checkbox',{name,exact:true}).check();await close();for(const [,id] of switches)await page.locator('#'+id).waitFor({state:'visible'});
 });
 await test('Pinned links provide direct navigation, editing, unpinning and undo',async()=>{
  await open('links');await page.getByLabel('Link name',{exact:true}).fill('Docs');await page.getByLabel('Website address',{exact:true}).fill('https://example.com/docs');await page.getByLabel('Link folder',{exact:true}).fill('Projects');await page.getByLabel('Pin to dashboard',{exact:true}).check();await button('Add link').click();await page.locator('#panel').getByText('Docs',{exact:true}).first().waitFor();await close();
  await context.route('https://example.com/**',route=>route.fulfill({status:200,contentType:'text/html',body:'<title>Pinned destination test</title>'}));await page.locator('#pinned-links').getByRole('link',{name:'Docs',exact:true}).click();await page.waitForURL('https://example.com/docs');await page.goto(url);await page.locator('#pinned-links').getByRole('link',{name:'Docs',exact:true}).waitFor();
  await open('links');await button('Pin Gmail to dashboard').click();await close();await page.locator('#pinned-links').getByRole('link',{name:'Gmail',exact:true}).waitFor();await open('links');await button('Unpin Gmail from dashboard').click();await button('Edit Docs').click();await page.getByLabel('Link name',{exact:true}).fill('Reference');await button('Save link').click();await page.getByRole('link',{name:/Reference/}).first().waitFor();await button('Remove Reference').click();await page.getByText('Link removed.',{exact:true}).waitFor();await button('Undo').click();await button('Edit Reference').waitFor();await close();await page.locator('#pinned-links').getByRole('link',{name:'Reference',exact:true}).waitFor();assert.equal(await page.locator('#pinned-links').getByRole('link',{name:'Gmail',exact:true}).count(),0);
 });
 await test('New dates and pins survive backup restoration and old backups still import',async()=>{
  const backup=await page.evaluate(async()=>{const m=await import('./lib/store.js');return m.exportBackup();});assert.equal(backup.state.schemaVersion,6);assert.ok(backup.state.workspaces.personal.links.some(l=>l.pinned));
  await page.evaluate(async()=>{const m=await import('./lib/store.js');await m.mutate(s=>{s.workspaces.personal.widgets.notes=false;s.workspaces.personal.links.forEach(l=>l.pinned=false);s.workspaces.personal.tasks.forEach(t=>t.dueDate='');});});
  await page.evaluate(async b=>{const m=await import('./lib/store.js');await m.importBackup(b);},backup);assert.equal((await snapshot()).workspaces.personal.tasks.find(t=>t.text==='An overdue task').dueDate,dates.prior);
  const file=path.join(qaDir,'legacy-backup.json');await fs.writeFile(file,JSON.stringify({format:'sebams-backup',version:1,state:legacy,images:[]}));await open('settings');await button('Data').click();await page.getByLabel('Choose a Sebams backup',{exact:true}).setInputFiles(file);await page.getByText('Backup restored.',{exact:true}).waitFor();assert.equal((await snapshot()).schemaVersion,6);assert.equal((await snapshot()).workspaces.personal.notes,'My existing private note');await button('Undo').click();await page.locator('#pinned-links').getByRole('link',{name:'Reference',exact:true}).waitFor({state:'attached'});await close();
 });
 await test('Concurrent date edits are detected instead of overwritten',async()=>{
  await open('tasks');await button('Edit Send design notes').click();await page.getByLabel('Edit task',{exact:true}).focus();const other=await context.newPage();await other.goto(url);await other.waitForFunction(()=>document.querySelector('#greeting').textContent.includes('Taylor'));await other.evaluate(async date=>{const m=await import('./lib/store.js');await m.mutate(s=>{s.workspaces.personal.tasks.find(t=>t.text==='Send design notes').dueDate=date;});},dates.next);
  await page.getByLabel('Edit task',{exact:true}).fill('Unsaved edit');await button('Save').click();await page.getByText('This task changed in another tab. Reopen it to edit.',{exact:true}).waitFor();assert.equal((await snapshot()).workspaces.personal.tasks.find(t=>t.text==='Send design notes').dueDate,dates.next);assert.equal(await page.getByLabel('Edit task',{exact:true}).inputValue(),'Unsaved edit');await button('Cancel').click();await other.close();await close();
 });
 await test('Neutral glass panels and pinned layouts remain usable at small sizes',async()=>{
  if(await page.locator('#toast').isVisible())await page.locator('#toast-close').click();
  await page.evaluate(async()=>{const m=await import('./lib/store.js');await m.mutate(s=>{s.prefs.backgroundMode='manual';s.prefs.backgroundId='alpine';s.workspaces.personal.links=Array.from({length:8},(_,i)=>({id:'pinned-'+i,title:['Reference','Mail','Calendar','Writing','Reading','Design','Research','Resources'][i],url:'https://example.com/'+i,folder:'Favorites',pinned:true}));});});
  await open('tasks');const glass=await page.locator('#panel').evaluate(e=>({background:getComputedStyle(e).backgroundColor,blur:getComputedStyle(e).backdropFilter}));assert.match(glass.background,/rgba\(24, 24, 27, 0.88\)/);assert.equal(glass.blur,'none');
  for(const [width,height] of [[1920,1080],[1366,768],[1024,640],[375,812]]){await page.setViewportSize({width,height});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const box=await page.locator('#panel').boundingBox();assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=width&&box.y+box.height<=height);}await page.setViewportSize({width:1440,height:900});await page.screenshot({path:path.join(qaDir,'tasks-preview.png')});await close();await page.screenshot({path:path.join(qaDir,'dashboard-preview.png')});await open('settings');await button('General').click();await page.locator('#panel').evaluate(e=>Promise.all(e.getAnimations().map(a=>a.finished.catch(()=>{}))));await page.screenshot({path:path.join(qaDir,'settings-preview.png')});await close();await page.reload();await page.locator('#pinned-links a').first().waitFor();assert.equal((await snapshot()).workspaces.personal.links.filter(l=>l.pinned).length,8);
 });
 assert.deepEqual(errors,[]);console.log('No uncaught page errors.');
}catch(e){console.error(e.stack);process.exitCode=1;if(!page.isClosed())await page.screenshot({path:path.join(qaDir,'upgrade-failure.png')});}
finally{await context.close();await fs.writeFile(path.join(qaDir,'upgrade-results.json'),JSON.stringify({results,errors},null,2));}
