import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.SEBAMS_PLAYWRIGHT_PACKAGE || 'playwright');
const root=fileURLToPath(new URL('../',import.meta.url));
const qaDir=process.env.SEBAMS_QA_DIR || path.join(root,'work','qa');
await fs.mkdir(qaDir,{recursive:true});
const chromePath=process.env.CHROME_PATH || (process.platform==='win32' ? 'C:/Program Files/Google/Chrome/Application/chrome.exe' : chromium.executablePath());
const profile=path.join(qaDir,'integration-profile-'+Date.now());
const results=[],errors=[];let context,page,extensionId;
async function launch(){context=await chromium.launchPersistentContext(profile,{executablePath:chromePath,headless:true,viewport:{width:1440,height:900},ignoreDefaultArgs:['--disable-extensions'],args:['--enable-unsafe-extension-debugging']});page=context.pages()[0]||await context.newPage();page.on('pageerror',e=>errors.push(e.message));const cdp=await context.browser().newBrowserCDPSession();const result=await cdp.send('Extensions.loadUnpacked',{path:root});extensionId=result.id;await page.goto('chrome://newtab/');await page.locator('#clock').filter({hasText:/\d+:\d+/}).waitFor();await page.waitForFunction(()=>document.querySelector('#greeting').textContent!=='Welcome to your space.');}
async function test(name,fn){try{await fn();results.push({name,status:'pass'});console.log('PASS',name);}catch(e){results.push({name,status:'fail',error:e.message});console.log('FAIL',name,e.message);throw e;}}
const open=async name=>{await page.locator('#'+name+'-open').click();await page.locator('#panel').waitFor({state:'visible'});if(name==='links'){await page.getByRole('button',{name:'Links options',exact:true}).click();await page.getByRole('button',{name:'Manage links',exact:true}).click();}};
const close=async()=>{await page.getByRole('button',{name:'Close panel',exact:true}).click();await page.locator('#panel').waitFor({state:'hidden'});};
const store=async()=>page.evaluate(async()=>{const m=await import('./lib/store.js');return (await m.exportBackup()).state;});
try{
await launch();
await test('Actual unpacked installation and new-tab override',async()=>{assert.ok(page.url().startsWith('chrome-extension://'));assert.ok(extensionId);assert.match(await page.title(),/Sebams/);});
await test('Onboarding and personalized greeting',async()=>{await page.getByPlaceholder('Your name (optional)').fill('Alex');await page.getByRole('button',{name:'Make yourself at home'}).click();await page.waitForFunction(()=>document.querySelector('#greeting').textContent.includes('Alex'));assert.equal(await page.locator('#welcome').isVisible(),false);});
await test('Daily focus save, edit, complete and unfinished rollover',async()=>{await page.getByLabel('Your main focus today').fill('Finish the creative brief');await page.getByRole('button',{name:'Save daily focus'}).click();await page.getByRole('button',{name:'Edit daily focus'}).click();await page.getByLabel('Your main focus today').fill('Give the creative brief a final pass');await page.getByRole('button',{name:'Save daily focus'}).click();await page.getByRole('button',{name:'Complete daily focus',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#focus-complete').classList.contains('done'));await page.getByRole('button',{name:'Mark daily focus unfinished'}).click();await page.evaluate(async()=>{const m=await import('./lib/store.js');await m.mutate(s=>{s.focus.day='2026-01-01';});});await page.reload();await page.getByText('Your unfinished focus is still here.').waitFor();await page.getByRole('button',{name:'Keep for today'}).click();await page.waitForFunction(()=>document.querySelector('#focus-rollover').hidden);});
await test('Tasks add, edit, priority, list, keyboard reorder, delete and undo',async()=>{await open('tasks');await page.getByLabel('New task', {exact:true}).fill('Draft introduction');await page.getByRole('button',{name:'Add',exact:true}).click();await page.getByLabel('New task', {exact:true}).fill('Review sources');await page.getByRole('button',{name:'Add',exact:true}).click();await page.locator('.task-row').filter({has:page.getByText('Review sources',{exact:true})}).hover();await page.getByRole('button',{name:'Move Review sources up',exact:true}).click();assert.equal((await store()).workspaces.personal.tasks[0].text,'Review sources');await page.getByRole('button',{name:'Edit Review sources',exact:true}).click();await page.getByLabel('Edit task', {exact:true}).fill('Review verified sources');await page.getByLabel('Task priority', {exact:true}).selectOption('high');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByLabel('Complete Review verified sources',{exact:true}).check();await page.getByRole('button',{name:'Delete Draft introduction',exact:true}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByText('Draft introduction',{exact:true}).waitFor();await close();});
await test('Notes autosave and workspace separation',async()=>{await open('notes');await page.locator('#notes-text').fill('One thoughtful idea, saved locally.');await page.getByRole('button',{name:'Save now'}).click();await close();await open('settings');await page.getByRole('button',{name:'Workspace',exact:true}).click();await page.getByRole('button',{name:'Work',exact:true}).click();await close();await open('notes');assert.equal(await page.locator('#notes-text').inputValue(),'');await close();await open('settings');await page.getByRole('button',{name:'Personal',exact:true}).click();await close();await open('notes');assert.equal(await page.locator('#notes-text').inputValue(),'One thoughtful idea, saved locally.');await close();});
await test('Multiple tabs concurrent writes and live updates',async()=>{const other=await context.newPage();await other.goto(`chrome-extension://${extensionId}/newtab.html`);await other.waitForFunction(()=>document.querySelector('#greeting').textContent.includes('Alex'));await Promise.all([page.evaluate(async()=>{const m=await import('./lib/store.js');await m.mutate(s=>{s.workspaces.personal.tasks.push({id:'concurrent-a',text:'Concurrent task',done:false,priority:'normal',list:'Inbox',dueDate:'',details:'',attachments:[],ai:null,sourceId:''});});}),other.evaluate(async()=>{const m=await import('./lib/store.js');await m.mutate(s=>{s.workspaces.personal.links.push({id:'concurrent-b',title:'Concurrent link',url:'https://example.com/',folder:'',pinned:false});});})]);await page.waitForFunction(async()=>{const m=await import('./lib/store.js');return m.getState().workspaces.personal.links.some(l=>l.id==='concurrent-b');});const s=await store();assert.ok(s.workspaces.personal.tasks.some(t=>t.id==='concurrent-a'));assert.ok(s.workspaces.personal.links.some(l=>l.id==='concurrent-b'));await other.close();});
await test('Unsafe link rejected and user text rendered safely',async()=>{await open('links');await page.getByLabel('Link name',{exact:true}).fill('<img src=x onerror=alert(1)>');await page.getByLabel('Website address',{exact:true}).fill('javascript:alert(1)');await page.getByRole('button',{name:'Add link',exact:true}).click();await page.getByText(/Use a website address/).waitFor();await page.getByLabel('Website address',{exact:true}).fill('https://example.org/');await page.getByRole('button',{name:'Add link',exact:true}).click();await page.getByText('<img src=x onerror=alert(1)>',{exact:true}).waitFor();assert.equal(await page.locator('.item-main img').count(),0);await close();});
await test('Background selection, favorites and custom quotes',async()=>{await page.locator('#background-open').click();await page.getByRole('button',{name:'Use Alpine stillness',exact:true}).click();await close();await page.getByRole('button',{name:'Favorite background',exact:true}).click();await page.locator('#quote-open').click();await page.getByLabel('Custom quote',{exact:true}).fill('Make room for good work.');await page.getByLabel('Quote author',{exact:true}).fill('Personal reminder');await page.getByRole('button',{name:'Add quote',exact:true}).click();await page.getByText('Make room for good work.',{exact:true}).waitFor();await close();});
await test('Habit tracking persists',async()=>{await open('habits');await page.getByLabel('New habit',{exact:true}).fill('Take a short walk');await page.getByRole('button',{name:'Add',exact:true}).click();await page.getByLabel('Complete Take a short walk today',{exact:true}).check();await close();assert.ok((await store()).workspaces.personal.habits.find(h=>h.text==='Take a short walk').days.length);});
await test('Timer pause/resume, focus view and suspended deadline recovery',async()=>{await open('timer');await page.getByRole('button',{name:'Start focus',exact:true}).click();await page.getByRole('button',{name:'Pause',exact:true}).click();const before=(await store()).timer.remainingMs;assert.ok(before>0);await page.getByRole('button',{name:'Resume',exact:true}).click();await page.getByLabel('Focus view · hide secondary widgets',{exact:true}).check();await close();assert.equal(await page.locator('#focus-view-bar').isVisible(),true);await page.getByRole('button',{name:'Leave focus view'}).click();await page.evaluate(async()=>{const m=await import('./lib/store.js');await m.mutate(s=>{s.timer.status='running';s.timer.endsAt=Date.now()-1000;s.timer.remainingMs=1000;});});await page.reload();await page.waitForFunction(async()=>{const m=await import('./lib/store.js');return m.getState().timer.status==='complete';});assert.equal((await store()).timer.mode,'break');});
await test('Backup export/import round trip and rejected unsafe backup',async()=>{const backup=await page.evaluate(async()=>{const m=await import('./lib/store.js');return m.exportBackup();});await fs.writeFile(path.join(qaDir,'test-backup.json'),JSON.stringify(backup));await page.evaluate(async()=>{const m=await import('./lib/store.js');await m.mutate(s=>{s.prefs.name='Changed';});});await open('settings');await page.getByRole('button',{name:'Data',exact:true}).click();await page.getByLabel('Choose a Sebams backup',{exact:true}).setInputFiles(path.join(qaDir,'test-backup.json'));await page.waitForFunction(()=>document.querySelector('#greeting').textContent.includes('Alex'));const rejected=await page.evaluate(async()=>{const m=await import('./lib/store.js');const b=await m.exportBackup();b.state.workspaces.personal.links[0].url='javascript:alert(1)';try{await m.importBackup(b);return false;}catch{return true;}});assert.equal(rejected,true);await close();});
await test('Offline new-tab assets and editing',async()=>{await context.setOffline(true);await page.reload();await page.waitForFunction(()=>document.querySelector('#greeting').textContent.includes('Alex'));assert.match(await page.locator('#background').evaluate(e=>e.style.backgroundImage),/url/);await open('tasks');await page.getByLabel('New task',{exact:true}).fill('Offline task');await page.getByRole('button',{name:'Add',exact:true}).click();await page.getByText('Offline task',{exact:true}).waitFor();await close();await context.setOffline(false);});
await test('Keyboard dialog navigation and Escape return',async()=>{await page.locator('#settings-open').focus();await page.keyboard.press('Enter');await page.locator('#panel').waitFor({state:'visible'});await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.querySelector('#panel').contains(document.activeElement)),true);await page.keyboard.press('Escape');await page.locator('#panel').waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>document.activeElement.id),'settings-open');
await open('tasks');await page.getByRole('button',{name:'Open Offline task',exact:true}).focus();await page.getByRole('button',{name:'Move Offline task up',exact:true}).focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.activeElement.getAttribute('aria-label')==='Move Offline task up');
await page.getByRole('button',{name:'Delete Offline task',exact:true}).focus();await page.keyboard.press('Enter');await page.getByText('Task deleted.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.querySelector('#panel').contains(document.activeElement)),true);await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByText('Offline task',{exact:true}).waitFor();await close();const target=await page.locator('#focus-complete').boundingBox();assert.ok(target.width>=40&&target.height>=40);
});
await test('Responsive layouts and zoom',async()=>{for(const [width,height] of [[1920,1080],[1366,768],[1024,640],[375,812]]){await page.setViewportSize({width,height});const layout=await page.evaluate(()=>{const a=document.querySelector('.center').getBoundingClientRect(),b=document.querySelector('.bottom-bar').getBoundingClientRect();return {overlap:a.bottom>b.top,overflow:document.documentElement.scrollWidth>innerWidth};});assert.equal(layout.overflow,false,`${width}px horizontal overflow`);assert.equal(layout.overlap,false,`${width}px center overlaps footer`);await open('tasks');const box=await page.locator('#panel').boundingBox();assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=width&&box.y+box.height<=height);await close();}await page.setViewportSize({width:1440,height:900});await page.screenshot({path:path.join(qaDir,'preview.png')});await page.goto('chrome-extension://'+extensionId+'/newtab.html'); await page.waitForFunction(()=>document.querySelector('#greeting').textContent.includes('Alex')); await page.evaluate(()=>chrome.tabs.getCurrent().then(tab=>chrome.tabs.setZoom(tab.id,2)));await open('settings');const zoomBox=await page.locator('#panel').boundingBox();assert.ok(zoomBox.x>=0&&zoomBox.y>=0);await close();await page.evaluate(()=>chrome.tabs.getCurrent().then(tab=>chrome.tabs.setZoom(tab.id,1)));});
await test('Full browser restart persistence and timer recovery',async()=>{await context.close();await launch();await page.waitForFunction(()=>document.querySelector('#greeting').textContent.includes('Alex'));const s=await store();assert.equal(s.workspaces.personal.notes,'One thoughtful idea, saved locally.');assert.ok(s.workspaces.personal.tasks.some(t=>t.text==='Offline task'));assert.equal(s.timer.mode,'break');assert.equal(s.timer.status,'complete');});
assert.deepEqual(errors,[]);console.log('No uncaught page errors.');
}catch(e){console.error(e.stack);if(page)await page.screenshot({path:path.join(qaDir,'test-failure.png')}).catch(()=>{});process.exitCode=1;}
finally{if(context)await context.close().catch(()=>{});await fs.writeFile(path.join(qaDir,'browser-results.json'),JSON.stringify({browser:'Chrome 154',results,errors},null,2));}





