import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.SEBAMS_PLAYWRIGHT_PACKAGE||'playwright');
const root=fileURLToPath(new URL('../',import.meta.url)),qaDir=process.env.SEBAMS_QA_DIR||path.join(root,'work','qa');await fs.mkdir(qaDir,{recursive:true});
const context=await chromium.launchPersistentContext(path.join(qaDir,'photos-profile-'+Date.now()),{executablePath:process.env.CHROME_PATH||(process.platform==='win32'?'C:/Program Files/Google/Chrome/Application/chrome.exe':chromium.executablePath()),headless:true,viewport:{width:1440,height:900},ignoreDefaultArgs:['--disable-extensions'],args:['--enable-unsafe-extension-debugging']});
const page=context.pages()[0]||await context.newPage(),cdp=await context.browser().newBrowserCDPSession(),loaded=await cdp.send('Extensions.loadUnpacked',{path:root});
const url=`chrome-extension://${loaded.id}/newtab.html`,results=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
const button=name=>page.getByRole('button',{name,exact:true});
const open=async name=>{await page.locator('#'+name+'-open').click();await page.locator('#panel').waitFor({state:'visible'});};
const close=async()=>{await button('Close panel').click();await page.locator('#panel').waitFor({state:'hidden'});};
const snapshot=()=>page.evaluate(async()=>{const m=await import('./lib/store.js');return(await m.exportBackup()).state;});
const cacheEntries=()=>page.evaluate(()=>new Promise((resolve,reject)=>{const req=indexedDB.open('sebams-v1');req.onsuccess=()=>{const db=req.result,read=db.transaction('photo-cache','readonly').objectStore('photo-cache').getAll();read.onsuccess=()=>{resolve(read.result.map(v=>({id:v.id,size:v.blob.size})));db.close();};read.onerror=()=>reject(read.error);};req.onerror=()=>reject(req.error);}));
async function test(name,fn){try{await fn();results.push({name,status:'pass'});console.log('PASS',name);}catch(error){results.push({name,status:'fail',error:error.message});throw error;}}
async function waitBackground(id){await page.waitForFunction(async id=>{const m=await import('./lib/store.js');const selected=m.getState().prefs.backgroundId;return selected===id&&document.querySelector('#background').style.backgroundImage.includes('blob:');},id);}
let photoRequests=0;page.on('request',r=>{if(r.url().includes('picsum.photos'))photoRequests++;});
const imageBytes=await fs.readFile(path.join(root,'assets/backgrounds/alpine.jpg'));
try{
 await test('Version 2 disk data and database version 1 migrate with dates, pins, notes and uploaded bytes intact',async()=>{
  await page.goto(`chrome-extension://${loaded.id}/assets/site-icon.svg`);
  await page.evaluate(async()=>{
    // Finish worker startup before replacing this isolated profile with a legacy database fixture.
    await(await import(chrome.runtime.getURL('lib/store.js'))).initStore();await chrome.runtime.sendMessage({type:'timer-sync'});
    await new Promise((resolve,reject)=>{const request=indexedDB.deleteDatabase('sebams-v1');request.onsuccess=resolve;request.onerror=()=>reject(request.error);});
    const {createDefaultState,APPEARANCE_DEFAULTS}=await import(chrome.runtime.getURL('lib/model.js'));const state=createDefaultState();state.schemaVersion=2;(await import(chrome.runtime.getURL('tests/fixtures.mjs'))).stripProduct(state);state.onboarded=true;state.prefs.name='Sebas';state.workspaces.personal.notes='My saved note';state.workspaces.personal.links=[{id:'roblox',title:'Roblox',url:'https://www.roblox.com/',folder:'',pinned:true},{id:'youtube',title:'YouTube',url:'https://www.youtube.com/',folder:'',pinned:true}];state.workspaces.personal.tasks=[{id:'dated',text:'Review the new design',done:false,priority:'normal',list:'Inbox',dueDate:'2026-10-10'}];delete state.photos;for(const key of Object.keys(APPEARANCE_DEFAULTS))delete state.prefs[key];
    const blob=await(await fetch(chrome.runtime.getURL('assets/backgrounds/alpine.jpg'))).blob();state.images=[{id:'old-upload',name:'My original photo',type:blob.type,size:blob.size}];
    await new Promise((resolve,reject)=>{const req=indexedDB.open('sebams-v1',1);req.onupgradeneeded=()=>{req.result.createObjectStore('data');req.result.createObjectStore('images');};req.onsuccess=()=>{const db=req.result,tx=db.transaction(['data','images'],'readwrite');tx.objectStore('data').put(state,'state');tx.objectStore('images').put(blob,'old-upload');tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);};req.onerror=()=>reject(req.error);});
  });
  await page.goto(url);await page.waitForFunction(()=>document.querySelector('#greeting').textContent.includes('Sebas'));const state=await snapshot();assert.equal(state.schemaVersion,6);assert.equal(state.workspaces.personal.notes,'My saved note');assert.equal(state.workspaces.personal.tasks[0].dueDate,'2026-10-10');assert.equal(state.workspaces.personal.links[0].pinned,true);assert.equal(await page.evaluate(async()=>{const m=await import('./lib/store.js');return(await m.getImage('old-upload')).size;}),imageBytes.length);assert.deepEqual(await cacheEntries(),[]);
 });
 await test('Online photos remain inactive and denied access makes no photo requests',async()=>{
  assert.equal(photoRequests,0);await page.evaluate(()=>{chrome.permissions.request=async()=>false;chrome.permissions.contains=async()=>false;});await open('background');await button('Enable online photos').click();await page.getByText('Photo access was declined. Your local backgrounds still work.',{exact:true}).waitFor();assert.equal(photoRequests,0);assert.equal((await snapshot()).photos.enabled,false);await close();
 });
 await test('Granted photo access loads the collection, supports favorites and next-scene navigation',async()=>{
  // Transport and permission fixtures are limited to this controlled failure/recovery suite.
  await context.route('https://picsum.photos/**',async route=>{const match=route.request().url().match(/\/id\/(\d+)/);if(route.request().url().endsWith('/info'))await route.fulfill({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify({id:match[1],author:'Test photographer',width:2500,height:1667,url:'https://unsplash.com/photos/test-'+match[1]})});else await route.fulfill({status:200,contentType:'image/jpeg',headers:{'access-control-allow-origin':'*'},body:imageBytes});});
  await page.evaluate(()=>{chrome.permissions.request=async()=>true;chrome.permissions.contains=async()=>true;});await open('background');await button('Enable online photos').click();await page.locator('.online-grid .photo-card').last().waitFor();assert.equal((await snapshot()).photos.items.length,12);await button('Use Mountain waters').click();await waitBackground('photo-1015');await button('Favorite Mountain waters').click();assert.ok((await snapshot()).prefs.favoriteBackgrounds.includes('photo-1015'));await page.getByLabel('Rotation frequency',{exact:true}).selectOption('hourly');await close();const before=(await snapshot()).prefs.backgroundId;await page.locator('#background-next').click();await page.waitForFunction(async prior=>(await import('./lib/store.js')).getState().prefs.backgroundId!==prior,before);assert.equal((await snapshot()).prefs.backgroundId,'photo-1018');
 });
 await test('Hourly and daily rotation update an already-open tab; new-tab cadence stays stable inside a tab',async()=>{
  await page.evaluate(async()=>{const m=await import('./lib/store.js');await m.mutate(s=>{s.prefs.backgroundMode='daily';s.prefs.backgroundCadence='hourly';});});const before=await page.locator('#scene-title').textContent();await page.clock.setFixedTime(new Date(Date.now()+3600000));await page.waitForFunction(prior=>document.querySelector('#scene-title').textContent!==prior,before);
  await page.evaluate(async()=>{const m=await import('./lib/store.js');await m.mutate(s=>{s.prefs.backgroundCadence='daily';});});const daily=await page.locator('#scene-title').textContent();await page.clock.setFixedTime(new Date(Date.now()+86400000));await page.waitForFunction(prior=>document.querySelector('#scene-title').textContent!==prior,daily);
  await page.evaluate(async()=>{const m=await import('./lib/store.js');await m.mutate(s=>{s.prefs.backgroundCadence='tab';});});const tab=await page.locator('#scene-title').textContent();await page.evaluate(async()=>{const m=await import('./lib/store.js');await m.mutate(s=>{s.prefs.name='Sebas';});});assert.equal(await page.locator('#scene-title').textContent(),tab);await page.clock.setFixedTime(new Date());
 });
 await test('Online cache is bounded, cached scenes survive offline reload, and uncached photos use a bundled scene',async()=>{
  await page.evaluate(async()=>{const m=await import('./lib/store.js');await m.mutate(s=>{s.prefs.backgroundMode='manual';s.prefs.backgroundId='alpine';});await m.clearPhotoCache();const blob=await(await fetch('assets/backgrounds/alpine.jpg')).blob();for(const id of ['photo-10','photo-15','photo-17','photo-28','photo-29','photo-1015'])await m.cachePhoto(id,blob);});const entries=await cacheEntries();assert.equal(entries.length,4);assert.ok(!entries.some(e=>e.id==='photo-10'));assert.ok(entries.reduce((n,e)=>n+e.size,0)<=16*1024*1024);
  await page.evaluate(async()=>{const m=await import('./lib/store.js');await m.mutate(s=>{s.prefs.backgroundId='photo-1015';});});await waitBackground('photo-1015');await context.unroute('https://picsum.photos/**');await context.setOffline(true);await page.reload();await waitBackground('photo-1015');await page.evaluate(async()=>{const m=await import('./lib/store.js');await m.mutate(s=>{s.prefs.backgroundId='photo-10';});});await page.getByText('Offline · showing a bundled scene',{exact:true}).waitFor();await page.waitForFunction(()=>document.querySelector('#background').style.backgroundImage.includes('alpine'));assert.match(await page.locator('#background').evaluate(e=>e.style.backgroundImage),/alpine/);assert.equal(await page.locator('#photo-credit').isVisible(),false);await context.setOffline(false);
 });
 await test('Appearance sliders persist, website icons use domains, and icon-only mode retains accessible link names',async()=>{
  await open('settings');await button('Appearance').click();for(const [label,value] of [['Panel opacity',48],['Background blur',3],['Clock size',90]])await page.getByLabel(label,{exact:true}).evaluate((e,value)=>{e.value=value;e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));},String(value));await page.waitForFunction(async()=>{const p=(await import('./lib/store.js')).getState().prefs;return p.panelOpacity===48&&p.backgroundBlur===3&&p.clockSize===90;});await page.getByLabel('Pinned shortcuts',{exact:true}).selectOption('icons');await close();await page.reload();await page.locator('#pinned-links a').first().waitFor();assert.equal((await snapshot()).prefs.panelOpacity,48);assert.equal(await page.locator('#pinned-links .pin-title').first().isVisible(),false);await page.locator('#pinned-links').getByRole('link',{name:'Roblox',exact:true}).waitFor();const src=await page.locator('#pinned-links .site-icon').first().getAttribute('src');assert.match(src,/domain=www.roblox.com/);assert.equal(await page.locator('#pinned-links .pin-monogram').count(),0);
  await open('settings');await button('Appearance').click();await page.getByRole('checkbox',{name:'Online website icons',exact:true}).uncheck();await close();assert.match(await page.locator('#pinned-links .site-icon').first().getAttribute('src'),/_favicon/);await open('settings');await button('Appearance').click();await button('Reset appearance').click();assert.equal((await snapshot()).prefs.panelOpacity,88);await page.getByRole('checkbox',{name:'Online website icons',exact:true}).check();await close();
 });
 await test('Eight vertical pins fit all four viewports and open their destinations with one click',async()=>{
  await page.evaluate(async()=>{const m=await import('./lib/store.js');await m.mutate(s=>{s.prefs.backgroundId='alpine';s.workspaces.personal.links=Array.from({length:8},(_,i)=>({id:'dock-'+i,title:['Roblox','YouTube','GitHub','Mail','Calendar','Reading','Design','Wikipedia'][i],url:['https://www.roblox.com/','https://www.youtube.com/','https://github.com/','https://mail.google.com/','https://calendar.google.com/','https://example.com/reading','https://example.com/design','https://www.wikipedia.org/'][i],folder:'',pinned:true}));});});
  for(const [width,height] of [[1920,1080],[1366,768],[1024,640],[375,812]]){await page.setViewportSize({width,height});const rects=await page.locator('#pinned-links a').evaluateAll(items=>items.map(e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height};}));assert.ok(rects[1].y>rects[0].y);assert.equal(rects[0].x,rects[1].x);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const nav=await page.locator('#pinned-links').boundingBox(),center=await page.locator('.center').boundingBox();assert.ok(nav.x+nav.width<=center.x,`Pins overlap central content at ${width}`);await open('settings');const dialog=await page.locator('#panel').boundingBox();assert.ok(dialog.x>=0&&dialog.x+dialog.width<=width);await close();}
  await page.setViewportSize({width:1440,height:900});await context.route('https://www.roblox.com/**',route=>route.fulfill({contentType:'text/html',body:'<title>Navigation fixture</title>'}));await page.locator('#pinned-links').getByRole('link',{name:'Roblox',exact:true}).click();await page.waitForURL('https://www.roblox.com/');await page.goto(url);
 });
 await test('Backup retains photo choices and appearance, and clearing cache turns off remote photos',async()=>{
  const backup=await page.evaluate(async()=>{const m=await import('./lib/store.js');return m.exportBackup();});assert.equal(backup.state.photos.items.length,12);assert.equal(backup.images.length,1);assert.ok(!JSON.stringify(backup).includes('savedAt'));
  await open('background');await button('Clear photo cache').click();assert.equal((await snapshot()).photos.enabled,false);assert.deepEqual(await cacheEntries(),[]);await close();await page.evaluate(async value=>{const m=await import('./lib/store.js');await m.importBackup(value);},backup);assert.equal((await snapshot()).photos.enabled,true);assert.equal((await snapshot()).prefs.panelOpacity,88);
 });
 if(process.env.SEBAMS_LIVE_PHOTOS==='1')await test('Real Picsum metadata, JPEG download, Chrome decoding and live website icons',async()=>{
  // Node queries the real service; Chrome uses the same downloaded JPEG through its normal local cache.
  // Headless Chrome cannot present the operating-system/browser host-permission consent dialog.
  const photos=await import(new URL('../lib/photos.js',import.meta.url));const collection=await photos.fetchPhotoCollection(null,true);assert.ok(collection.items.length>0,'Real service returned a usable collection');const photo=collection.items.find(p=>p.photoId==='1015'),blob=await photos.fetchPhotoBlob(photo);await fs.writeFile(path.join(qaDir,'real-photo-response.json'),JSON.stringify(collection,null,2));
  await page.evaluate(async({collection,data})=>{chrome.permissions.contains=async()=>true;const m=await import('./lib/store.js');const bytes=Uint8Array.from(atob(data),c=>c.charCodeAt(0));await m.cachePhoto('photo-1015',new Blob([bytes],{type:'image/jpeg'}));await m.mutate(s=>{s.photos=collection;s.prefs.backgroundMode='manual';s.prefs.backgroundId='photo-1015';s.prefs.name='Sebas';s.prefs.backgroundBlur=0;s.prefs.panelOpacity=58;s.prefs.panelBlur=24;s.workspaces.personal.links=s.workspaces.personal.links.slice(0,5);s.focus.text='Crear algo que valga la pena';});},{collection,data:Buffer.from(await blob.arrayBuffer()).toString('base64')});await page.addInitScript(()=>{chrome.permissions.contains=async()=>true;});await page.reload();await waitBackground('photo-1015');await page.locator('#photo-credit').waitFor();await page.locator('#pinned-links img').evaluateAll(images=>Promise.race([Promise.all(images.map(image=>image.decode().catch(()=>{}))),new Promise(resolve=>setTimeout(resolve,10000))]));assert.ok(await page.locator('#pinned-links img').evaluateAll(images=>images.slice(0,2).every(image=>image.naturalWidth>=16&&image.src.includes('google.com'))),'Real Roblox and YouTube icons loaded');await page.screenshot({path:path.join(qaDir,'dashboard-preview.png')});
  await page.evaluate(()=>{chrome.permissions.contains=async()=>true;});await open('background');await page.locator('.online-grid img').first().evaluate(image=>image.decode().catch(()=>{}));await page.locator('#panel').evaluate(e=>Promise.all(e.getAnimations().map(a=>a.finished.catch(()=>{}))));await page.screenshot({path:path.join(qaDir,'photos-preview.png')});await close();await open('settings');await button('Appearance').click();await page.locator('#panel').evaluate(e=>Promise.all(e.getAnimations().map(a=>a.finished.catch(()=>{}))));await page.screenshot({path:path.join(qaDir,'appearance-preview.png')});await close();
 });
 assert.deepEqual(errors,[]);console.log('No uncaught page errors.');
}catch(error){console.error(error.stack);process.exitCode=1;if(!page.isClosed())await page.screenshot({path:path.join(qaDir,'photos-failure.png')});}
finally{await context.close();await fs.writeFile(path.join(qaDir,'photos-results.json'),JSON.stringify({results,errors},null,2));}
