import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.SEBAMS_PLAYWRIGHT_PACKAGE||'playwright');
const root=fileURLToPath(new URL('../',import.meta.url)),qa=process.env.SEBAMS_QA_DIR||path.join(root,'work','product');await fs.mkdir(qa,{recursive:true});
const context=await chromium.launchPersistentContext(path.join(qa,'product-profile-'+Date.now()),{executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,viewport:{width:1440,height:900},ignoreDefaultArgs:['--disable-extensions'],args:['--enable-unsafe-extension-debugging']});
const page=context.pages()[0],cdp=await context.browser().newBrowserCDPSession(),{id}=await cdp.send('Extensions.loadUnpacked',{path:root}),url=`chrome-extension://${id}/newtab.html`,results=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));const b=name=>page.getByRole('button',{name,exact:true}),store=()=>page.evaluate(async()=>(await import('./lib/store.js')).getState());
const open=async()=>{await page.locator('#tasks-open').click();await page.locator('#panel').waitFor({state:'visible'});},close=async()=>{await action('Close panel');await page.locator('#panel').waitFor({state:'hidden'});};
const action=async name=>{await b(name).click();await page.waitForTimeout(100);};
const check=async(name,fn)=>{try{await fn();results.push({name,status:'pass'});console.log('PASS',name);}catch(error){results.push({name,status:'fail',error:error.message});throw error;}};
let taskId,today,tomorrow,examDate;
try{
  await page.goto(url);await page.locator('#welcome-skip').click();await page.locator('#welcome').waitFor({state:'hidden'});await page.evaluate(async()=>{await(await import('./lib/store.js')).mutate(s=>{s.prefs.remindersOnOpen=false;s.prefs.onlineSiteIcons=false;});});
  ({today,tomorrow,examDate}=await page.evaluate(async()=>{const {dayString,addDays}=await import('./lib/planner.js');const today=dayString(new Date());return{today,tomorrow:addDays(today,1),examDate:addDays(today,7)};}));
  await check('Task checklist supports creation, edit, completion, removal and reload',async()=>{
    await open();await page.getByLabel('New task',{exact:true}).fill('Practice mathematics');await page.getByLabel('Date for new task').fill(tomorrow);await action('Add');await action('Open Practice mathematics');taskId=(await store()).workspaces.personal.tasks[0].id;
    await page.getByLabel('New checklist step').fill('Read notes');await action('Add step');await page.getByLabel('New checklist step').fill('Try exercises');await action('Add step');await page.getByLabel('Step Read notes',{exact:true}).fill('Read chapter');await page.getByLabel('Step Read notes',{exact:true}).press('Tab');await page.getByLabel('Finish step Read chapter').check();await action('Remove step Try exercises');assert.equal((await store()).workspaces.personal.tasks[0].subtasks.length,1);await close();await page.reload();await open();await action('Open Practice mathematics');assert.equal(await page.getByLabel('Finish step Read chapter').isChecked(),true);
  });
  await check('Task estimates and elapsed tracking persist across reload and stop on completion',async()=>{
    await page.getByLabel('Estimated minutes').fill('45');await page.getByLabel('Estimated minutes').press('Tab');await action('Track task time');assert.ok((await store()).workspaces.personal.tasks[0].activeSince!==null);await close();await page.reload();await open();await action('Open Practice mathematics');assert.equal(await page.getByLabel('Estimated minutes').inputValue(),'45');assert.equal(await b('Track task time').textContent(),'Pause tracking');await action('Track task time');const t=(await store()).workspaces.personal.tasks[0];assert.equal(t.activeSince,null);assert.ok(t.timeSpentMs>0);
  });
  await check('Repeating task completes once and creates a clean next occurrence',async()=>{
    await page.locator('.task-options summary').click();await page.getByLabel('Repeat task').selectOption('weekly');await action('Save schedule');await action('Mark complete');let tasks=(await store()).workspaces.personal.tasks;assert.equal(tasks.length,2);assert.equal(tasks[0].done,true);assert.equal(tasks[1].done,false);assert.equal(tasks[1].subtasks[0].done,false);assert.equal(tasks[1].attachments.length,0);assert.ok(tasks[0].completedAt>0);await action('Mark unfinished');await action('Mark complete');assert.equal((await store()).workspaces.personal.tasks.length,2);
  });
  await check('Future reminders save and use the configured lead time',async()=>{
    await action('Back to tasks');await action('Show all tasks');const next=(await store()).workspaces.personal.tasks[1];await b('Open '+next.text).last().click();await page.waitForTimeout(100);await page.locator('.task-options summary').click();await action('Before due date');const value=await page.getByLabel('Task reminder').inputValue();assert.match(value,/T09:00$/);await action('Save schedule');assert.ok((await store()).workspaces.personal.tasks[1].reminderAt>Date.now());await action('Clear reminder');await action('Save schedule');assert.equal((await store()).workspaces.personal.tasks[1].reminderAt,null);
  });
  await check('Reference photos remain local and AI defaults to hints without photos',async()=>{
    await page.getByLabel('Attach task photos').setInputFiles(path.join(root,'assets/backgrounds/alpine.jpg'));await page.locator('.task-photo img').waitFor();assert.equal(await page.getByLabel('Include reference photos in this AI request').isChecked(),false);assert.match(await page.getByLabel('AI assistance mode').inputValue(),/pistas/);assert.equal((await store()).workspaces.personal.tasks[1].attachments.length,1);await action('View photo alpine.jpg');await page.locator('.reference-viewer img').waitFor();await page.waitForFunction(()=>document.querySelector('.reference-viewer img').naturalWidth>0);await action('Close reference photo');
  });
  await check('Task templates save a checklist and create independent tasks without photos or answers',async()=>{
    await page.getByText('Save as a reusable template',{exact:true}).click();await page.getByLabel('Save task as template').fill('Revision routine');await action('Save template');await action('Show Templates');await action('Use template Revision routine');const tasks=(await store()).workspaces.personal.tasks,created=tasks.at(-1);assert.equal(tasks.length,3);assert.equal(created.estimateMinutes,45);assert.equal(created.attachments.length,0);assert.equal(created.ai,null);assert.equal(created.dueDate,'');assert.equal(created.subtasks[0].done,false);assert.notEqual(created.subtasks[0].id,tasks[1].subtasks[0].id);
  });
  await check('Templates allow editing, independent creation and deletion',async()=>{
    await action('Show Templates');await page.getByText('Edit template',{exact:true}).click();await page.getByLabel('Rename template Revision routine').fill('Homework routine');await page.getByLabel('Edit template title Revision routine').fill('Prepare homework');await action('Save template changes');await b('Use template Homework routine').waitFor();await action('Use template Homework routine');await page.getByRole('heading',{name:'Prepare homework',exact:true}).waitFor();await action('Show Templates');await page.getByText('Create a template',{exact:true}).click();await page.getByLabel('New template name').fill('Reading');await page.getByLabel('Template task title',{exact:true}).fill('Read a chapter');await page.getByLabel('Template checklist').fill('Read\nTake notes');await action('Create template');await action('Delete template Reading');assert.equal((await store()).workspaces.personal.templates.length,1);
  });
  await check('Exam planner distributes topic tasks before the exam and calendar opens sessions',async()=>{
    await action('Show Exam planner');await page.getByLabel('Exam title').fill('Science exam');await page.getByLabel('Exam date',{exact:true}).fill(examDate);await page.getByLabel('Exam topics').fill('Cells\nGenetics\nEcology');await action('Create study plan');const w=(await store()).workspaces.personal;assert.equal(w.exams.length,1);assert.equal(w.tasks.filter(t=>t.planId===w.exams[0].id).length,4);assert.ok(w.tasks.filter(t=>t.kind==='study').every(t=>t.dueDate>=today&&t.dueDate<examDate));await action('Show Calendar');assert.equal(await page.locator('.calendar-day').count(),7);await page.locator('[aria-label^="Calendar task Study:"]').first().click();await page.getByRole('heading',{name:/Study:/}).waitFor();
  });
  await check('Weekly progress counts new completion dates by subject',async()=>{
    await action('Mark complete');await action('Show Progress');assert.equal(Number(await page.locator('.progress-summary strong').textContent()),2);assert.match(await page.locator('.progress-row').first().textContent(),/2 completed/);await action('← Previous');assert.equal(Number(await page.locator('.progress-summary strong').textContent()),0);await action('This week');await page.screenshot({path:path.join(qa,'progress-desktop.png')});
  });
  await check('Command palette searches details, lists and links and supports keyboard opening',async()=>{
    await close();await page.keyboard.press('Control+k');await page.getByLabel('Search Sebams',{exact:true}).fill('Science exam');await page.getByLabel('Search Sebams',{exact:true}).press('Enter');await page.getByRole('heading',{name:'Science exam',exact:true}).waitFor();await close();await page.keyboard.press('Control+k');await page.getByLabel('Search Sebams',{exact:true}).fill('Exam planner');await page.keyboard.press('Enter');await page.getByRole('heading',{name:'Exam planner',exact:true}).waitFor();await close();await page.locator('#search-commands').click();await page.getByLabel('Search Sebams',{exact:true}).fill('Wikipedia');assert.equal(await page.locator('.command-result').count(),1);await page.keyboard.press('Escape');
  });
  await check('Website capture creates Inbox task with selection and source using the actual capture handler',async()=>{
    const captured=await page.evaluate(async()=>{const {saveCapture}=await import('./lib/capture.js');return saveCapture({selectionText:'Review this paragraph',pageUrl:'https://example.com/lesson'},{title:'Example lesson'});});const task=(await store()).workspaces.personal.tasks.find(t=>t.id===captured.id);assert.equal(task.list,'Inbox');assert.equal(task.text,'Review this paragraph');assert.match(task.details,/https:\/\/example.com\/lesson/);const worker=context.serviceWorkers().find(w=>w.url().includes(id));assert.ok(worker);await worker.evaluate(async()=>{await chrome.contextMenus.update('sebams-capture',{title:'Add to Sebams Tasks'});});
  });
  await check('Desktop notification scheduler delivers once and reschedules after edits',async()=>{
    const worker=context.serviceWorkers().find(w=>w.url().includes(id));await worker.evaluate(()=>{self.qaNotifications=[];chrome.permissions.contains=async()=>true;chrome.notifications={create:async(id,options)=>{self.qaNotifications.push({id,options});return id;}};});await page.evaluate(async()=>{const m=await import('./lib/store.js');await m.mutate(s=>{s.prefs.remindersEnabled=true;const t=s.workspaces.personal.tasks.find(t=>t.text==='Review this paragraph');t.reminderAt=Date.now()-1000;});await chrome.runtime.sendMessage({type:'task-sync'});});assert.equal((await worker.evaluate(()=>self.qaNotifications)).length,1);await page.evaluate(()=>chrome.runtime.sendMessage({type:'task-sync'}));assert.equal((await worker.evaluate(()=>self.qaNotifications)).length,1);assert.ok((await store()).workspaces.personal.tasks.find(t=>t.text==='Review this paragraph').remindedAt>0);await page.evaluate(async()=>{await(await import('./lib/store.js')).mutate(s=>{s.workspaces.personal.tasks.find(t=>t.text==='Review this paragraph').reminderAt=Date.now()+3600000;});await chrome.runtime.sendMessage({type:'task-sync'});});const alarm=await page.evaluate(()=>chrome.alarms.get('sebams-task-reminders'));assert.ok(alarm.scheduledTime>Date.now());
  });
  await check('Failed desktop delivery keeps its reminder pending and backs off instead of looping',async()=>{
    const worker=context.serviceWorkers().find(w=>w.url().includes(id));await worker.evaluate(()=>{self.qaAttempts=0;chrome.notifications.create=async()=>{self.qaAttempts++;throw Error('Simulated notification failure');};});await page.evaluate(async()=>{await(await import('./lib/store.js')).mutate(s=>{s.workspaces.personal.tasks.find(t=>t.text==='Review this paragraph').reminderAt=Date.now()-1000;});await chrome.runtime.sendMessage({type:'task-sync'});});assert.equal(await worker.evaluate(()=>self.qaAttempts),1);assert.equal((await store()).workspaces.personal.tasks.find(t=>t.text==='Review this paragraph').remindedAt,null);await page.evaluate(()=>chrome.runtime.sendMessage({type:'task-sync'}));assert.equal(await worker.evaluate(()=>self.qaAttempts),1);assert.ok((await page.evaluate(()=>chrome.alarms.get('sebams-task-reminders'))).scheduledTime>Date.now());await worker.evaluate(()=>{chrome.notifications.create=async(id,options)=>{self.qaNotifications.push({id,options});return id;};});await page.evaluate(async()=>{await(await import('./lib/store.js')).mutate(s=>{s.workspaces.personal.tasks.find(t=>t.text==='Review this paragraph').reminderAt=null;});});
  });
  await check('Pins support logos, names, no glass, direct removal and undo',async()=>{
    await page.evaluate(async()=>{await(await import('./lib/store.js')).mutate(s=>{s.workspaces.personal.links[0].pinned=true;s.prefs.pinStyle='icons';s.prefs.pinGlass=false;});});await page.locator('#pinned-links a').waitFor();assert.equal(await page.locator('.pin-title').first().isVisible(),false);assert.equal(await page.locator('.pin-link').evaluate(n=>getComputedStyle(n).backdropFilter),'none');await page.locator('#settings-open').click();await action('Appearance');await page.getByLabel('Pinned shortcuts',{exact:true}).selectOption('names');await close();assert.equal(await page.locator('#pinned-links .site-icon').first().isVisible(),false);assert.equal(await page.locator('.pin-title').first().isVisible(),true);await page.locator('#pinned-links').hover();await action('Remove shortcut Gmail');assert.equal((await store()).workspaces.personal.links.some(l=>l.id==='link-mail'),false);await action('Undo');assert.equal((await store()).workspaces.personal.links[0].pinned,true);
  });
  await check('Renaming and deleting a subject preserves its templates and plans through undo',async()=>{
    await page.evaluate(async()=>{await(await import('./lib/store.js')).mutate(s=>{const w=s.workspaces.personal;w.lists.push('Science');w.templates[0].list='Science';w.exams[0].list='Science';for(const t of w.tasks)if(t.planId===w.exams[0].id)t.list='Science';});});await open();await action('Show list Science');await action('Rename list');await page.getByLabel('List name',{exact:true}).fill('Biology');await action('Save name');let w=(await store()).workspaces.personal;assert.equal(w.templates[0].list,'Biology');assert.equal(w.exams[0].list,'Biology');await action('Delete list');w=(await store()).workspaces.personal;assert.equal(w.templates[0].list,'Inbox');assert.equal(w.exams[0].list,'Inbox');await action('Undo');w=(await store()).workspaces.personal;assert.equal(w.templates[0].list,'Biology');assert.equal(w.exams[0].list,'Biology');await close();
  });
  await check('Backups preserve checklists, plans, templates, dates and time without connection secrets',async()=>{
    const backup=await page.evaluate(async()=>(await import('./lib/store.js')).exportBackup());await page.evaluate(async backup=>{const m=await import('./lib/store.js');await m.mutate(s=>{s.workspaces.personal.templates=[];s.workspaces.personal.exams=[];s.workspaces.personal.tasks=[];});await m.importBackup(backup);},backup);const state=await store();assert.equal(state.workspaces.personal.tasks.length,backup.state.workspaces.personal.tasks.length);assert.deepEqual(state.workspaces.personal.templates,backup.state.workspaces.personal.templates);assert.deepEqual(state.workspaces.personal.exams,backup.state.workspaces.personal.exams);assert.equal(state.workspaces.personal.tasks[0].timeSpentMs,backup.state.workspaces.personal.tasks[0].timeSpentMs);assert.equal(backup.state.prefs.remindersEnabled,true);
  });
  await check('New views and task details remain contained on narrow screens',async()=>{
    await open();for(const [width,height] of [[1440,900],[1024,640],[375,812],[320,568]]){await page.setViewportSize({width,height});for(const view of ['Calendar','Exam planner','Templates','Progress']){await action('Show '+view);await page.locator('#panel').evaluate(p=>Promise.all(p.getAnimations().map(a=>a.finished.catch(()=>{}))));const g=await page.locator('#panel').evaluate(p=>({overflow:p.scrollWidth>p.clientWidth+1,doc:document.documentElement.scrollWidth>innerWidth,bottom:p.getBoundingClientRect().bottom}));assert.equal(g.overflow,false,`${width}px ${view} panel overflow`);assert.equal(g.doc,false,`${width}px ${view} document overflow`);assert.ok(g.bottom<=height+1);}}
    await page.setViewportSize({width:1440,height:900});await action('Show Calendar');await page.screenshot({path:path.join(qa,'calendar-desktop.png')});await action('Show Exam planner');await page.screenshot({path:path.join(qa,'exam-planner-desktop.png')});await action('Show all tasks');await b('Open Practice mathematics').first().click();await page.waitForTimeout(100);await page.screenshot({path:path.join(qa,'task-details-desktop.png')});await page.setViewportSize({width:375,height:812});await page.screenshot({path:path.join(qa,'task-details-mobile.png')});
  });
  assert.deepEqual(errors,[]);console.log('PASS No page errors');results.push({name:'No browser page errors',status:'pass'});
}catch(error){await page.screenshot({path:path.join(qa,'product-failure.png')}).catch(()=>{});console.error(error);process.exitCode=1;}
finally{await fs.mkdir(path.join(root,'tests/results'),{recursive:true});await fs.writeFile(path.join(root,'tests/results/product.json'),JSON.stringify({results,errors},null,2));await context.close();}
