import test from 'node:test';import assert from 'node:assert/strict';
import {createDefaultState,localDay,rollover,validateState,validateBackup} from '../lib/model.js';
import {remaining,startTimer,pauseTimer,reconcileTimer,resetTimer,advanceTimer} from '../lib/timer.js';
import {fetchWeather,searchCities} from '../lib/weather.js';

test('defaults are valid, separate workspaces do not share arrays',()=>{const s=createDefaultState();assert.equal(validateState(s),s);s.workspaces.work.tasks.push({id:'a',text:'Work task',done:false,priority:'normal',list:'Inbox',dueDate:'',details:'',attachments:[],ai:null,sourceId:''});assert.equal(s.workspaces.personal.tasks.length,0);assert.match(localDay(),/^\d{4}-\d{2}-\d{2}$/);});
test('unfinished focus survives repeated day changes until an explicit choice',()=>{const s=createDefaultState();s.focus={text:'Finish writing',day:'2026-09-30',done:false,pending:false};rollover(s,'2026-10-01');rollover(s,'2026-10-04');assert.equal(s.focus.text,'Finish writing');assert.equal(s.focus.day,'2026-09-30');assert.equal(s.focus.pending,true);assert.equal(s.focusArchive.length,0);});
test('completed focus archives once and clears for a new day',()=>{const s=createDefaultState();s.focus={text:'Finish writing',day:'2026-09-30',done:true,pending:false};rollover(s,'2026-10-01');rollover(s,'2026-10-01');assert.equal(s.focusArchive.length,1);assert.equal(s.focus.text,'');assert.equal(s.focus.day,'2026-10-01');});
test('strict backup validation rejects unknown fields, unsafe URLs and impossible dates',()=>{const s=createDefaultState(),b={format:'sebams-backup',version:1,state:s,images:[]};assert.equal(validateBackup(b),b);for(const mutate of [s=>{s.prefs.extra=true;},s=>{s.workspaces.personal.links[0].url='javascript:alert(1)';},s=>{s.focus.day='2026-02-31';},s=>{s.timer.status='running';s.timer.endsAt=null;},s=>{s.workspaces.personal.notes='x'.repeat(20001);}]){const copy=structuredClone(b);mutate(copy.state);assert.throws(()=>validateBackup(copy));}const bad=JSON.parse(JSON.stringify(b));Object.defineProperty(bad.state.prefs,'__proto__',{value:true,enumerable:true});assert.throws(()=>validateBackup(bad));});
test('timer pause and resume use the saved remaining duration',()=>{let t=startTimer(createDefaultState().timer,1000);assert.equal(t.endsAt,1501000);assert.equal(remaining(t,61000),1440000);t=pauseTimer(t,61000);assert.equal(t.status,'paused');assert.equal(remaining(t,999999),1440000);t=startTimer(t,5000000);assert.equal(t.endsAt,6440000);});
test('timer recovers an expired deadline once and waits for the next session',()=>{const t=startTimer(createDefaultState().timer,1000);const recovered=reconcileTimer(t,90000000);assert.equal(recovered.status,'complete');assert.equal(recovered.mode,'break');assert.equal(recovered.remainingMs,300000);assert.equal(recovered.completedAt,1501000);assert.deepEqual(reconcileTimer(recovered,100000000),recovered);assert.equal(resetTimer(recovered).status,'idle');assert.equal(advanceTimer(recovered).mode,'work');});
test('weather reuses a fresh matching cache and never fabricates a failed reading',async()=>{const original=globalThis.fetch,city={name:'Berlin',label:'Berlin',latitude:52.52,longitude:13.41},cached={cityKey:'52.52,13.41',tempC:12,code:3,updatedAt:Date.now()};let calls=0;globalThis.fetch=async()=>{calls++;throw new TypeError('Failed to fetch');};try{assert.equal(await fetchWeather(city,cached),cached);assert.equal(calls,0);await assert.rejects(()=>fetchWeather(city,cached,true),/offline/);assert.equal(cached.tempC,12);assert.equal(calls,1);}finally{globalThis.fetch=original;}});
test('weather validates real response shape and handles service errors',async()=>{const original=globalThis.fetch,city={name:'Berlin',label:'Berlin',latitude:52.52,longitude:13.41};try{globalThis.fetch=async()=>new Response(JSON.stringify({current:{temperature_2m:15.4,weather_code:3}}));const c=await fetchWeather(city);assert.equal(c.tempC,15.4);assert.equal(c.cityKey,'52.52,13.41');globalThis.fetch=async()=>new Response(JSON.stringify({current:{temperature_2m:null,weather_code:3}}));await assert.rejects(()=>fetchWeather(city),/unavailable reading/);globalThis.fetch=async()=>new Response('{}',{status:503});await assert.rejects(()=>fetchWeather(city),/temporarily unavailable/);await assert.rejects(()=>searchCities('x'),/at least two/);}finally{globalThis.fetch=original;}});

