import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {createUpdater} from '../updater.mjs';
import {normalizeRepository,fetchGithubRelease} from '../github-release.mjs';
import {createLocalServer} from '../server.mjs';
const digest=b=>createHash('sha256').update(b).digest('hex');
async function fixture(t){
 const base=await fs.mkdtemp(path.join(os.tmpdir(),'sebams-github-test-'));t.after(async()=>{if(!(await fs.realpath(base)).startsWith(await fs.realpath(os.tmpdir())+path.sep))throw Error('Unsafe cleanup');await fs.rm(base,{recursive:true,force:true});});
 const name='Sebams — A little space to focus',bundle={format:'sebams-github-release',version:'1.8.0',notes:'Shared release',files:[['manifest.json',JSON.stringify({name,manifest_version:3,version:'1.8.0'})],['app.js','Shared new code']].map(([path,text])=>{const bytes=Buffer.from(text);return{path,size:bytes.length,sha256:digest(bytes),data:bytes.toString('base64')};})};
 const calls=[];let redirect='',status=200,tag='v1.8.0',assetURL='https://github.com/example/sebams/releases/download/v1.8.0/sebams-update.json';
 const fetchImpl=async(url,options)=>{calls.push({url,options});const raw=Buffer.from(JSON.stringify(bundle));if(url.startsWith('https://api.github.com/'))return new Response(JSON.stringify({tag_name:tag,draft:false,prerelease:false,assets:[{name:'sebams-update.json',size:raw.length,digest:'sha256:'+digest(raw),browser_download_url:assetURL}]}),{status});if(url.startsWith('https://github.com/')&&redirect)return new Response(null,{status:302,headers:{location:redirect}});return new Response(raw);};
 async function pc(label){const target=path.join(base,label),release=path.join(base,label+'-release'),config=path.join(base,label+'-updates.json');await fs.mkdir(target);await fs.mkdir(release);await fs.writeFile(path.join(target,'manifest.json'),JSON.stringify({name,manifest_version:3,version:'1.7.0'}));await fs.writeFile(path.join(target,'app.js'),'Old '+label);await fs.writeFile(config,JSON.stringify({extensionDirectory:target,releaseDirectory:release,githubRepository:'example/sebams'}));return {target,config,updater:createUpdater({configurationFile:config,fetchImpl})};}
 return {base,bundle,calls,fetchImpl,pc,setRedirect:v=>{redirect=v;},setStatus:v=>{status=v;},setTag:v=>{tag=v;},setURL:v=>{assetURL=v;}};
}
test('Repository URLs normalize and reject credentials, foreign hosts and unsafe names',()=>{assert.equal(normalizeRepository(' https://github.com/Example/Sebams.git/ '),'Example/Sebams');assert.equal(normalizeRepository('example/sebams'),'example/sebams');assert.equal(normalizeRepository(''),'');for(const value of ['https://github.com.evil.test/a/b','https://token@github.com/a/b','https://github.com/a/b?token=secret','../repo','a/b/tree/main','http://github.com/a/b'])assert.throws(()=>normalizeRepository(value));});
test('The same shared release updates two independent PCs and backs up each old version',async t=>{const f=await fixture(t),a=await f.pc('pc-a'),b=await f.pc('pc-b');for(const pc of [a,b]){const checked=await pc.updater.check('1.7.0');assert.equal(checked.source,'github');assert.equal(checked.repository,'example/sebams');await pc.updater.install(checked);assert.equal(await fs.readFile(path.join(pc.target,'app.js'),'utf8'),'Shared new code');assert.equal((await pc.updater.check('1.8.0')).available,false);}assert.equal((await fs.readdir(path.join(f.base,'Sebams-version-backups'))).length,2);for(const {options} of f.calls){assert.equal(options.redirect,'manual');assert.equal(options.headers.Authorization,undefined);assert.ok(options.signal);}});
test('Remote file corruption and traversal are rejected without changing the installed version',async t=>{const f=await fixture(t),pc=await f.pc('pc');f.bundle.files[1].data=Buffer.from('Corrupted bytes').toString('base64');f.bundle.files[1].size=15;await assert.rejects(pc.updater.check('1.7.0'),/integrity check/);f.bundle.files[1].path='../app.js';await assert.rejects(pc.updater.check('1.7.0'),/unsafe file path/);assert.equal(await fs.readFile(path.join(pc.target,'app.js'),'utf8'),'Old pc');});
test('A changed GitHub release requires a fresh check before installation',async t=>{const f=await fixture(t),pc=await f.pc('pc'),checked=await pc.updater.check('1.7.0');f.bundle.notes='Changed after checking';await assert.rejects(pc.updater.install(checked),/changed/);assert.equal(await fs.readFile(path.join(pc.target,'app.js'),'utf8'),'Old pc');});
test('Only the configured GitHub repository and approved asset CDN redirects are downloaded',async t=>{const f=await fixture(t);f.setRedirect('https://release-assets.githubusercontent.com/example/file?signature=test');assert.equal((await fetchGithubRelease('example/sebams',{fetchImpl:f.fetchImpl})).bundle.version,'1.8.0');f.setRedirect('https://evil.test/asset');await assert.rejects(fetchGithubRelease('example/sebams',{fetchImpl:f.fetchImpl}),/unexpected download/);assert.equal(f.calls.some(c=>c.url.includes('evil.test')),false);f.setRedirect('');f.setURL('https://github.com/other/sebams/releases/download/v1.8.0/sebams-update.json');await assert.rejects(fetchGithubRelease('example/sebams',{fetchImpl:f.fetchImpl}),/different repository/);});
test('No release, rate limits and release tag mismatch have actionable errors',async t=>{const f=await fixture(t);f.setStatus(404);await assert.rejects(fetchGithubRelease('example/sebams',{fetchImpl:f.fetchImpl}),/No public release/);f.setStatus(403);await assert.rejects(fetchGithubRelease('example/sebams',{fetchImpl:f.fetchImpl}),/limited update checks/);f.setStatus(200);f.setTag('v2.0.0');f.setURL('https://github.com/example/sebams/releases/download/v2.0.0/sebams-update.json');await assert.rejects(fetchGithubRelease('example/sebams',{fetchImpl:f.fetchImpl}),/tag does not match/);});
test('Remote duplicate names, noncanonical base64 and oversized files fail before installation',async t=>{const f=await fixture(t),pc=await f.pc('pc');f.bundle.files.push({...f.bundle.files[1],path:'APP.JS'});await assert.rejects(pc.updater.check('1.7.0'),/invalid files/);f.bundle.files.pop();f.bundle.files[1].data='!!!!';await assert.rejects(pc.updater.check('1.7.0'),/invalid file data/);f.bundle.files[1].size=11*1024*1024;await assert.rejects(pc.updater.check('1.7.0'),/invalid files/);});
test('Source endpoints require pairing and cannot modify this PC’s installation paths',async t=>{const f=await fixture(t),pc=await f.pc('pc'),server=createLocalServer({token:'test-token',solver:{configured:false},store:{},updater:pc.updater});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const url='http://127.0.0.1:'+server.address().port,headers={Authorization:'Bearer test-token','Content-Type':'application/json'};assert.equal((await fetch(url+'/updates/source')).status,401);let result=await(await fetch(url+'/updates/source',{headers})).json();assert.deepEqual(result,{configured:true,source:'github',repository:'example/sebams'});assert.equal(JSON.stringify(result).includes(pc.target),false);assert.equal((await fetch(url+'/updates/source',{method:'POST',headers,body:JSON.stringify({repository:'new-owner/sebams',extensionDirectory:'C:/foreign'})})).status,400);result=await(await fetch(url+'/updates/source',{method:'POST',headers,body:JSON.stringify({repository:'https://github.com/new-owner/sebams'})})).json();assert.equal(result.repository,'new-owner/sebams');const config=JSON.parse(await fs.readFile(pc.config));assert.equal(config.extensionDirectory,pc.target);assert.equal(config.githubRepository,'new-owner/sebams');assert.equal((await pc.updater.setSource({repository:''})).source,'local');});
