import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {createUpdater,compareVersions} from '../updater.mjs';
import {createLocalServer} from '../server.mjs';
const digest=b=>createHash('sha256').update(b).digest('hex');
async function fixture(t,options={}){const base=await fs.mkdtemp(path.join(os.tmpdir(),'sebams-update-test-')),target=path.join(base,'extension'),release=path.join(base,'release');t.after(async()=>{const resolved=await fs.realpath(base);if(!resolved.startsWith(await fs.realpath(os.tmpdir())+path.sep))throw Error('Unsafe test cleanup');await fs.rm(base,{recursive:true,force:true});});await fs.mkdir(target);await fs.mkdir(path.join(release,'files'),{recursive:true});const manifest={manifest_version:3,name:'Sebams — A little space to focus',version:'1.6.0'};await fs.writeFile(path.join(target,'manifest.json'),JSON.stringify(manifest));await fs.writeFile(path.join(target,'app.js'),'old');const files=[];for(const [name,text] of [['manifest.json',JSON.stringify({...manifest,version:'1.7.0'})],['app.js','new']]){const bytes=Buffer.from(text);await fs.writeFile(path.join(release,'files',name),bytes);files.push({path:name,size:bytes.length,sha256:digest(bytes)});}const metadata={format:'sebams-local-release',version:'1.7.0',notes:'Update fixture',files};const config=path.join(base,'updates.json');await fs.writeFile(config,JSON.stringify({extensionDirectory:target,releaseDirectory:release}));const updater=createUpdater({configurationFile:config,...options});return {base,target,release,metadata,updater,write:()=>fs.writeFile(path.join(release,'release.json'),JSON.stringify(metadata))};}
test('Versions compare numerically, including all four Chrome components',()=>{assert.equal(compareVersions('1.10','1.9.99'),1);assert.equal(compareVersions('1.7','1.7.0.0'),0);assert.equal(compareVersions('1.7.0.1','1.7'),1);assert.throws(()=>compareVersions('../1','1'));assert.throws(()=>compareVersions('1.65536','1'));});
test('Local install validates release, swaps all files and retains previous version',async t=>{const f=await fixture(t);await f.write();const checked=await f.updater.check('1.6.0');assert.equal(checked.available,true);const result=await f.updater.install(checked);assert.equal(result.backupCreated,true);assert.equal(await fs.readFile(path.join(f.target,'app.js'),'utf8'),'new');const [backup]=await fs.readdir(path.join(f.base,'Sebams-version-backups'));assert.equal(await fs.readFile(path.join(f.base,'Sebams-version-backups',backup,'app.js'),'utf8'),'old');const latest=await f.updater.check('1.6.0');assert.equal(latest.needsReload,true);assert.equal((await f.updater.check('1.7.0')).available,false);await assert.rejects(f.updater.install(checked),/already installed/);});
test('Corrupt payload and unsafe paths never modify installed files',async t=>{const f=await fixture(t);await f.write();const checked=await f.updater.check('1.6.0');await fs.writeFile(path.join(f.release,'files/app.js'),'bad');await assert.rejects(f.updater.install(checked),/integrity check/);assert.equal(await fs.readFile(path.join(f.target,'app.js'),'utf8'),'old');f.metadata.files[1].path='../app.js';await f.write();await assert.rejects(f.updater.check('1.6.0'),/unsafe file path/);});
test('Changed metadata and downgrade attempts are rejected',async t=>{const f=await fixture(t);await f.write();const checked=await f.updater.check('1.6.0');f.metadata.notes='changed';await f.write();await assert.rejects(f.updater.install(checked),/changed/);const current=JSON.parse(await fs.readFile(path.join(f.target,'manifest.json'),'utf8'));current.version='2.0.0';await fs.writeFile(path.join(f.target,'manifest.json'),JSON.stringify(current));await assert.rejects(f.updater.install(await f.updater.check('2.0.0')),/already installed/);assert.equal(await fs.readFile(path.join(f.target,'app.js'),'utf8'),'old');});
test('Failed replacement rolls back the original folder and removes staging files',async t=>{let calls=0;const f=await fixture(t,{renameFile:async(a,b)=>{calls++;if(calls===2)throw Error('Simulated lock');await fs.rename(a,b);}});await f.write();await assert.rejects(f.updater.install(await f.updater.check('1.6.0')),/Simulated lock/);assert.equal(await fs.readFile(path.join(f.target,'app.js'),'utf8'),'old');assert.equal((await fs.readdir(f.base)).some(p=>p.startsWith('.sebams-update-')),false);});
test('Parallel installs serialize and return a clear busy response',async t=>{let unblock;const block=new Promise(r=>{unblock=r;});let moves=0;const f=await fixture(t,{renameFile:async(a,b)=>{if(++moves===1)await block;await fs.rename(a,b);}});await f.write();const check=await f.updater.check('1.6.0'),first=f.updater.install(check);await assert.rejects(f.updater.install(check),/already being installed/);unblock();await first;});
test('Update endpoints require pairing authentication and report missing configuration honestly',async t=>{const server=createLocalServer({token:'test-token',solver:{configured:false},store:{}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const url=`http://127.0.0.1:${server.address().port}`;assert.equal((await fetch(url+'/updates?current=1.6.0')).status,401);const response=await fetch(url+'/updates?current=1.6.0',{headers:{Authorization:'Bearer test-token'}});assert.equal(response.status,200);assert.deepEqual((await response.json()).available,false);});
