import {createTask,finalizeTasks} from './planner.js';
import {selectReminders} from './reminders.js';
import {createDefaultState,validateState,validateBackup,upgradeState,IMAGE_TYPES,MAX_IMAGE_BYTES,MAX_TOTAL_IMAGE_BYTES,taskAttachmentMetadata} from './model.js';
let databasePromise,cached,channel;const listeners=new Set();
function database(){if(!databasePromise)databasePromise=new Promise((resolve,reject)=>{const req=indexedDB.open('sebams-v1',3);req.onupgradeneeded=()=>{for(const name of ['data','images','photo-cache','task-attachments','private'])if(!req.result.objectStoreNames.contains(name))req.result.createObjectStore(name);};req.onsuccess=()=>{req.result.onversionchange=()=>{req.result.close();databasePromise=null;};resolve(req.result);};req.onerror=()=>{databasePromise=null;reject(Error('Local storage is unavailable.'));};req.onblocked=()=>reject(Error('Close other Sebams tabs and try again.'));});return databasePromise;}
function request(req){return new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
function complete(tx){return new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error||Error('Local storage could not save your changes.'));tx.onabort=()=>reject(tx.error||Error('Your changes were not saved.'));});}
function publish(state,announce=true){if(!cached||state.revision>=cached.revision){cached=structuredClone(state);for(const listener of listeners){try{listener(structuredClone(cached));}catch(e){console.error('Sebams view update failed',e);}}}if(announce)channel?.postMessage({revision:state.revision});}
async function refresh(){const db=await database();const tx=db.transaction('data','readonly');const done=complete(tx);const state=await request(tx.objectStore('data').get('state'));await done;if(state)publish(upgradeState(state),false);}
export async function initStore(){const db=await database(),tx=db.transaction('data','readwrite'),done=complete(tx);let state;try{const stored=await request(tx.objectStore('data').get('state'));state=stored?upgradeState(stored):createDefaultState();if(!stored||stored.schemaVersion!==state.schemaVersion){if(stored)state.revision++;tx.objectStore('data').put(state,'state');}validateState(state);}catch(e){tx.abort();await done.catch(()=>{});throw e;}await done;publish(state,false);if(!channel&&typeof BroadcastChannel!=='undefined'){channel=new BroadcastChannel('sebams-changes');channel.onmessage=()=>refresh().catch(()=>{});}if(typeof window!=='undefined'&&!window.__sebamsStorageFocus){window.__sebamsStorageFocus=true;window.addEventListener('focus',()=>refresh().catch(()=>{}));document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh().catch(()=>{});});}return getState();}
export function getState(){if(!cached)throw Error('Sebams storage is still opening.');return structuredClone(cached);}
export function subscribe(listener){listeners.add(listener);return()=>listeners.delete(listener);}
export async function mutate(mutator){const db=await database();const tx=db.transaction('data','readwrite');const done=complete(tx);let next;try{next=upgradeState((await request(tx.objectStore('data').get('state')))||createDefaultState());const before=structuredClone(next);const result=mutator(next);if(result&&typeof result.then==='function')throw Error('Storage changes must be synchronous.');finalizeTasks(next,before);next.revision++;validateState(next);tx.objectStore('data').put(next,'state');}catch(e){tx.abort();await done.catch(()=>{});throw e;}await done;publish(next);return getState();}
async function validImage(blob){if(!IMAGE_TYPES.includes(blob.type)||blob.size<1||blob.size>MAX_IMAGE_BYTES)throw Error('Choose a JPG, PNG, or WebP image smaller than 8 MB.');const b=new Uint8Array(await blob.slice(0,16).arrayBuffer());const valid=blob.type==='image/png'?b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71:blob.type==='image/jpeg'?b[0]===255&&b[1]===216&&b[2]===255:String.fromCharCode(...b.slice(0,4))==='RIFF'&&String.fromCharCode(...b.slice(8,12))==='WEBP';if(!valid)throw Error('The image contents do not match its file type.');if(typeof createImageBitmap==='function'){let bitmap;try{bitmap=await createImageBitmap(blob);if(bitmap.width>12000||bitmap.height>12000||bitmap.width*bitmap.height>40000000)throw Error('Choose an image under 40 million pixels and 12,000 pixels on each side.');}finally{bitmap?.close();}}}
export async function putImage(file){await validImage(file);const meta={id:crypto.randomUUID(),name:(file.name||'Personal scene').slice(0,150),type:file.type,size:file.size};const db=await database(),tx=db.transaction(['data','images'],'readwrite'),done=complete(tx);let next;try{next=upgradeState((await request(tx.objectStore('data').get('state')))||createDefaultState());if(next.images.length>=12||next.images.reduce((n,i)=>n+i.size,0)+file.size>MAX_TOTAL_IMAGE_BYTES)throw Error('Your image collection is full. Remove a scene before adding another (24 MB total).');next.images.push(meta);next.revision++;validateState(next);tx.objectStore('images').put(file,meta.id);tx.objectStore('data').put(next,'state');}catch(e){tx.abort();await done.catch(()=>{});throw e;}await done;publish(next);return meta;}
export async function getImage(id){const db=await database(),tx=db.transaction('images','readonly'),done=complete(tx);const blob=await request(tx.objectStore('images').get(id));await done;return blob;}
export async function getCachedPhoto(id){const db=await database(),tx=db.transaction('photo-cache','readwrite'),done=complete(tx);const store=tx.objectStore('photo-cache'),value=await request(store.get(id));if(value){value.savedAt=Date.now();store.put(value,id);}await done;return value?.blob;}
export async function cachePhoto(id,blob){if(!/^photo-\d{1,5}$/.test(id)||blob.size>4*1024*1024)throw Error('This photo could not be cached.');await validImage(blob);const db=await database(),tx=db.transaction('photo-cache','readwrite'),done=complete(tx);try{const store=tx.objectStore('photo-cache'),items=await request(store.getAll());const others=items.filter(item=>item.id!==id).sort((a,b)=>a.savedAt-b.savedAt);while(others.length>=4)store.delete(others.shift().id);store.put({id,blob,savedAt:Date.now()},id);}catch(error){tx.abort();await done.catch(()=>{});throw error;}await done;}
export async function clearPhotoCache(){const db=await database(),tx=db.transaction('photo-cache','readwrite'),done=complete(tx);tx.objectStore('photo-cache').clear();await done;}
export async function removeImage(id){const db=await database(),tx=db.transaction(['data','images'],'readwrite'),done=complete(tx);const next=upgradeState(await request(tx.objectStore('data').get('state')));next.images=next.images.filter(i=>i.id!==id);next.prefs.favoriteBackgrounds=next.prefs.favoriteBackgrounds.filter(i=>i!==id);if(next.prefs.backgroundId===id)next.prefs.backgroundId='alpine';next.revision++;tx.objectStore('images').delete(id);tx.objectStore('data').put(validateState(next),'state');await done;publish(next);}
function dataURL(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('An image could not be included in the backup.'));r.readAsDataURL(blob);});}
export async function exportBackup(){const db=await database(),tx=db.transaction(['data','images','task-attachments'],'readonly'),done=complete(tx);const state=upgradeState(await request(tx.objectStore('data').get('state'))),metadata=taskAttachmentMetadata(state);const [blobs,taskBlobs]=await Promise.all([Promise.all(state.images.map(i=>request(tx.objectStore('images').get(i.id)))),Promise.all(metadata.map(i=>request(tx.objectStore('task-attachments').get(i.id))))]);await done;const records=async(metas,values)=>Promise.all(metas.map(async(meta,index)=>{if(!values[index])throw Error('A stored photo is missing. Remove or reattach it before backing up.');return{id:meta.id,name:meta.name,type:meta.type,data:await dataURL(values[index])};}));const [images,attachments]=await Promise.all([records(state.images,blobs),records(metadata,taskBlobs)]);return{format:'sebams-backup',version:2,state,images,attachments};}
export async function importBackup(value,expectedRevision=null){const backup=validateBackup(structuredClone(value));const decode=async images=>{const blobs=[];for(const image of images){const encoded=image.data.slice(image.data.indexOf(',')+1);let bytes;try{bytes=Uint8Array.from(atob(encoded),c=>c.charCodeAt(0));}catch{throw Error('A backup image is malformed.');}const blob=new Blob([bytes],{type:image.type});await validImage(blob);blobs.push(blob);}return blobs;};const [blobs,taskBlobs]=await Promise.all([decode(backup.images),decode(backup.attachments)]);
  const db=await database(),tx=db.transaction(['data','images','task-attachments'],'readwrite'),done=complete(tx);let next;try{const current=await request(tx.objectStore('data').get('state'));if(expectedRevision!==null&&current?.revision!==expectedRevision)throw Error('Sebams changed after the restore. Save a current backup before replacing it again.');next=backup.state;next.revision=(current?.revision||0)+1;for(const id of ['personal','work','study'])next.workspaces[id].notesRevision=Math.max(next.workspaces[id].notesRevision,current?.workspaces[id]?.notesRevision||0)+1;tx.objectStore('images').clear();tx.objectStore('task-attachments').clear();tx.objectStore('data').delete('attachment-orphans');backup.images.forEach((meta,index)=>tx.objectStore('images').put(blobs[index],meta.id));backup.attachments.forEach((meta,index)=>tx.objectStore('task-attachments').put(taskBlobs[index],meta.id));tx.objectStore('data').put(validateState(next),'state');}catch(e){tx.abort();await done.catch(()=>{});throw e;}await done;publish(next);return getState();}

function taskIn(state,workspaceId,taskId){if(!['personal','work','study'].includes(workspaceId))throw Error('Choose a Sebams workspace.');const task=state.workspaces[workspaceId].tasks.find(t=>t.id===taskId);if(!task)throw Error('This task was deleted in another tab.');return task;}
export async function putTaskAttachment(workspaceId,taskId,file){await validImage(file);const meta={id:crypto.randomUUID(),name:(file.name||'Task photo').slice(0,150),type:file.type,size:file.size};const db=await database(),tx=db.transaction(['data','task-attachments'],'readwrite'),done=complete(tx);let next;try{next=upgradeState(await request(tx.objectStore('data').get('state')));const task=taskIn(next,workspaceId,taskId);if(task.attachments.length>=4)throw Error('Attach up to four photos to a task.');task.attachments.push(meta);next.revision++;validateState(next);tx.objectStore('task-attachments').put(file,meta.id);tx.objectStore('data').put(next,'state');}catch(error){tx.abort();await done.catch(()=>{});throw error;}await done;publish(next);return meta;}
export async function getTaskAttachment(id){const db=await database(),tx=db.transaction('task-attachments','readonly'),done=complete(tx);const blob=await request(tx.objectStore('task-attachments').get(id));await done;return blob;}
export async function removeTaskAttachment(workspaceId,taskId,id){const db=await database(),tx=db.transaction(['data','task-attachments'],'readwrite'),done=complete(tx);let next;try{next=upgradeState(await request(tx.objectStore('data').get('state')));const task=taskIn(next,workspaceId,taskId);if(!task.attachments.some(image=>image.id===id))throw Error('This task photo was already removed.');task.attachments=task.attachments.filter(image=>image.id!==id);next.revision++;tx.objectStore('task-attachments').delete(id);tx.objectStore('data').put(validateState(next),'state');}catch(error){tx.abort();await done.catch(()=>{});throw error;}await done;publish(next);}
export async function getBridgeConfig(){const db=await database(),tx=db.transaction('private','readonly'),done=complete(tx);const value=await request(tx.objectStore('private').get('bridge'));await done;return value||{token:''};}
export async function getUpdatePreferences(){const db=await database(),tx=db.transaction('private','readonly'),done=complete(tx);const value=await request(tx.objectStore('private').get('updates'));await done;return value||{autoCheck:false,lastCheckedAt:0,availableVersion:''};}
export async function claimOpenReminders(now=Date.now()){
  const db=await database(),tx=db.transaction(['data','private'],'readwrite'),done=complete(tx);let items;
  try{const state=upgradeState(await request(tx.objectStore('data').get('state'))),store=tx.objectStore('private'),receipts=(await request(store.get('reminder-receipts')))||[];items=selectReminders(state,receipts,now);const keys=new Set(items.map(r=>r.key));store.put([...receipts.filter(r=>!keys.has(r.key)),...items.map(r=>({key:r.key,until:now+300000}))].slice(-3000),'reminder-receipts');}catch(e){tx.abort();await done.catch(()=>{});throw e;}await done;return items;
}
export async function settleOpenReminders(keys,until){
  if(!Array.isArray(keys)||keys.length>8||!keys.every(k=>typeof k==='string'&&k.length<=300)||!Number.isFinite(until)||until<0)throw Error('Invalid reminder choice.');const db=await database(),tx=db.transaction('private','readwrite'),done=complete(tx);const store=tx.objectStore('private'),receipts=(await request(store.get('reminder-receipts')))||[],selected=new Set(keys);store.put([...receipts.filter(r=>!selected.has(r.key)),...keys.map(key=>({key,until}))].slice(-3000),'reminder-receipts');await done;
}
export async function setUpdateReload(value){if(!value||value.tabId!==null&&(!Number.isInteger(value.tabId)||value.tabId<0)||!Number.isFinite(value.at))throw Error('The update could not prepare a reload.');const db=await database(),tx=db.transaction('private','readwrite'),done=complete(tx);tx.objectStore('private').put({tabId:value.tabId,at:value.at},'update-reload');await done;}
export async function takeUpdateReload(){const db=await database(),tx=db.transaction('private','readwrite'),done=complete(tx);const store=tx.objectStore('private'),value=await request(store.get('update-reload'));store.delete('update-reload');await done;return value;}
export async function patchUpdatePreferences(patch){
  if(!patch||Object.keys(patch).some(k=>!['autoCheck','lastCheckedAt','availableVersion'].includes(k)))throw Error('Invalid update settings.');
  const db=await database(),tx=db.transaction('private','readwrite'),done=complete(tx);let value;
  try{const store=tx.objectStore('private'),current=(await request(store.get('updates')))||{autoCheck:false,lastCheckedAt:0,availableVersion:''};value={...current,...patch};if(typeof value.autoCheck!=='boolean'||!Number.isFinite(value.lastCheckedAt)||value.lastCheckedAt<0||typeof value.availableVersion!=='string'||value.availableVersion.length>25)throw Error('Invalid update settings.');store.put(value,'updates');}catch(error){tx.abort();await done.catch(()=>{});throw error;}await done;return value;
}
export async function setUpdatePreferences(value){if(!value||typeof value.autoCheck!=='boolean'||!Number.isFinite(value.lastCheckedAt)||value.lastCheckedAt<0||typeof value.availableVersion!=='string'||value.availableVersion.length>25)throw Error('Invalid update settings.');return patchUpdatePreferences({autoCheck:value.autoCheck,lastCheckedAt:value.lastCheckedAt,availableVersion:value.availableVersion});}
export async function setBridgeConfig(value){if(!value||Object.keys(value).join(',')!=='token'||typeof value.token!=='string'||value.token&&(!/^[A-Za-z0-9_-]{32,128}$/.test(value.token)||value.token.startsWith('sk-')||value.token.startsWith('AIza')))throw Error('Use the Sebams Bridge connection code, not an OpenAI API key.');const db=await database(),tx=db.transaction('private','readwrite'),done=complete(tx);tx.objectStore('private').put({token:value.token},'bridge');await done;}

export async function reconcileBridgeTasks(tasks){
  if(!Array.isArray(tasks)||tasks.length>300)throw Error('The Bridge returned an invalid task collection.');
  const ids=new Set();for(const task of tasks){if(!task||Object.keys(task).some(k=>!['id','text','priority','dueDate','list','workspace','details'].includes(k))||typeof task.id!=='string'||!task.id.trim()||task.id.length>100||ids.has(task.id)||!['personal','work','study'].includes(task.workspace)||typeof task.list!=='string'||!task.list.trim()||task.list.length>40)throw Error('The Bridge returned an invalid task.');ids.add(task.id);const probe=createDefaultState();probe.workspaces[task.workspace].lists=[task.list];probe.workspaces[task.workspace].tasks=[createTask({id:task.id,text:task.text,priority:task.priority,dueDate:task.dueDate,list:task.list,details:task.details??'',done:false,attachments:[],ai:null,sourceId:task.id})];validateState(probe);}
  const db=await database(),tx=db.transaction('data','readwrite'),done=complete(tx);let next,added=0;const acceptedIds=[];
  try{next=upgradeState(await request(tx.objectStore('data').get('state')));const received=new Set((await request(tx.objectStore('data').get('bridge-received')))||[]);for(const w of Object.values(next.workspaces))for(const task of w.tasks)if(task.sourceId)received.add(task.sourceId);
    for(const item of tasks){acceptedIds.push(item.id);if(received.has(item.id))continue;const w=next.workspaces[item.workspace];if(w.tasks.length>=300)throw Error('A task workspace is full. Remove a task before receiving more.');if(!w.lists.includes(item.list)){if(w.lists.length>=20)throw Error('A task workspace has 20 lists. Free a list before receiving more.');w.lists.push(item.list);}w.tasks.push(createTask({id:crypto.randomUUID(),text:item.text,priority:item.priority,dueDate:item.dueDate,list:item.list,details:item.details??'',done:false,attachments:[],ai:null,sourceId:item.id}));received.add(item.id);added++;}
    if(added){next.revision++;tx.objectStore('data').put(validateState(next),'state');}tx.objectStore('data').put([...received].slice(-3000),'bridge-received');
  }catch(error){tx.abort();await done.catch(()=>{});throw error;}await done;if(added)publish(next);return{acceptedIds,added};
}
// Mark orphans first, then remove them on a later sweep after every Undo window expires.
export async function pruneTaskAttachments(now=Date.now()){
  const db=await database(),tx=db.transaction(['data','task-attachments'],'readwrite'),done=complete(tx);
  try{const state=upgradeState(await request(tx.objectStore('data').get('state'))),refs=new Set(taskAttachmentMetadata(state).map(i=>i.id)),previous=new Map((await request(tx.objectStore('data').get('attachment-orphans')))||[]),keys=await request(tx.objectStore('task-attachments').getAllKeys()),orphans=[];for(const id of keys){if(refs.has(id))continue;const first=previous.get(id)??now;if(now-first>=60000)tx.objectStore('task-attachments').delete(id);else orphans.push([id,first]);}tx.objectStore('data').put(orphans,'attachment-orphans');}catch(error){tx.abort();await done.catch(()=>{});throw error;}await done;
}

